/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.parser.antlr;

import com.google.inject.Inject;
import edu.upb.lp.parser.antlr.internal.InternalJarvisProjectParser;
import edu.upb.lp.services.JarvisProjectGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class JarvisProjectParser extends AbstractAntlrParser {

	@Inject
	private JarvisProjectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJarvisProjectParser createParser(XtextTokenStream stream) {
		return new InternalJarvisProjectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public JarvisProjectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JarvisProjectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
