/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject.impl;

import edu.upb.lp.jarvisProject.FunctionInt;
import edu.upb.lp.jarvisProject.JarvisProjectPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Function Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FunctionIntImpl extends FunctionImpl implements FunctionInt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FunctionIntImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JarvisProjectPackage.Literals.FUNCTION_INT;
  }

} //FunctionIntImpl
