/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject.impl;

import edu.upb.lp.jarvisProject.IntPowerExpression;
import edu.upb.lp.jarvisProject.JarvisProjectPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Int Power Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntPowerExpressionImpl extends ExpressionImpl implements IntPowerExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntPowerExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JarvisProjectPackage.Literals.INT_POWER_EXPRESSION;
  }

} //IntPowerExpressionImpl
