/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject.impl;

import edu.upb.lp.jarvisProject.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class JarvisProjectFactoryImpl extends EFactoryImpl implements JarvisProjectFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static JarvisProjectFactory init()
  {
    try
    {
      JarvisProjectFactory theJarvisProjectFactory = (JarvisProjectFactory)EPackage.Registry.INSTANCE.getEFactory(JarvisProjectPackage.eNS_URI);
      if (theJarvisProjectFactory != null)
      {
        return theJarvisProjectFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new JarvisProjectFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public JarvisProjectFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case JarvisProjectPackage.PROGRAM: return createProgram();
      case JarvisProjectPackage.FUNCTION: return createFunction();
      case JarvisProjectPackage.TYPED_PARAM: return createTypedParam();
      case JarvisProjectPackage.STATEMENT: return createStatement();
      case JarvisProjectPackage.INITIALIZATION: return createInitialization();
      case JarvisProjectPackage.ASSIGNMENT: return createAssignment();
      case JarvisProjectPackage.PRINT: return createPrint();
      case JarvisProjectPackage.WHILE: return createWhile();
      case JarvisProjectPackage.IF: return createIf();
      case JarvisProjectPackage.IPP: return createIpp();
      case JarvisProjectPackage.IMM: return createImm();
      case JarvisProjectPackage.INT_VALUE: return createIntValue();
      case JarvisProjectPackage.STRING_VALUE: return createStringValue();
      case JarvisProjectPackage.BOOLEAN_VALUE: return createBooleanValue();
      case JarvisProjectPackage.EXPRESSION: return createExpression();
      case JarvisProjectPackage.BOOLEAN_OR_EXPRESSION: return createBooleanOrExpression();
      case JarvisProjectPackage.BOOLEAN_AND_EXPRESSION: return createBooleanAndExpression();
      case JarvisProjectPackage.BOOLEAN_EQUALITY_EXPRESSION: return createBooleanEqualityExpression();
      case JarvisProjectPackage.INT_ADDITIVE_EXPRESSION: return createIntAdditiveExpression();
      case JarvisProjectPackage.INT_MULTIPLICATIVE_EXPRESSION: return createIntMultiplicativeExpression();
      case JarvisProjectPackage.INT_POWER_EXPRESSION: return createIntPowerExpression();
      case JarvisProjectPackage.STRING_CONCAT_EXPRESSION: return createStringConcatExpression();
      case JarvisProjectPackage.VARIABLE_REF: return createVariableRef();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Program createProgram()
  {
    ProgramImpl program = new ProgramImpl();
    return program;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Function createFunction()
  {
    FunctionImpl function = new FunctionImpl();
    return function;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TypedParam createTypedParam()
  {
    TypedParamImpl typedParam = new TypedParamImpl();
    return typedParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Statement createStatement()
  {
    StatementImpl statement = new StatementImpl();
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initialization createInitialization()
  {
    InitializationImpl initialization = new InitializationImpl();
    return initialization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Assignment createAssignment()
  {
    AssignmentImpl assignment = new AssignmentImpl();
    return assignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Print createPrint()
  {
    PrintImpl print = new PrintImpl();
    return print;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public While createWhile()
  {
    WhileImpl while_ = new WhileImpl();
    return while_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public If createIf()
  {
    IfImpl if_ = new IfImpl();
    return if_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ipp createIpp()
  {
    IppImpl ipp = new IppImpl();
    return ipp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Imm createImm()
  {
    ImmImpl imm = new ImmImpl();
    return imm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntValue createIntValue()
  {
    IntValueImpl intValue = new IntValueImpl();
    return intValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringValue createStringValue()
  {
    StringValueImpl stringValue = new StringValueImpl();
    return stringValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanValue createBooleanValue()
  {
    BooleanValueImpl booleanValue = new BooleanValueImpl();
    return booleanValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanOrExpression createBooleanOrExpression()
  {
    BooleanOrExpressionImpl booleanOrExpression = new BooleanOrExpressionImpl();
    return booleanOrExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanAndExpression createBooleanAndExpression()
  {
    BooleanAndExpressionImpl booleanAndExpression = new BooleanAndExpressionImpl();
    return booleanAndExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BooleanEqualityExpression createBooleanEqualityExpression()
  {
    BooleanEqualityExpressionImpl booleanEqualityExpression = new BooleanEqualityExpressionImpl();
    return booleanEqualityExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntAdditiveExpression createIntAdditiveExpression()
  {
    IntAdditiveExpressionImpl intAdditiveExpression = new IntAdditiveExpressionImpl();
    return intAdditiveExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntMultiplicativeExpression createIntMultiplicativeExpression()
  {
    IntMultiplicativeExpressionImpl intMultiplicativeExpression = new IntMultiplicativeExpressionImpl();
    return intMultiplicativeExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntPowerExpression createIntPowerExpression()
  {
    IntPowerExpressionImpl intPowerExpression = new IntPowerExpressionImpl();
    return intPowerExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringConcatExpression createStringConcatExpression()
  {
    StringConcatExpressionImpl stringConcatExpression = new StringConcatExpressionImpl();
    return stringConcatExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableRef createVariableRef()
  {
    VariableRefImpl variableRef = new VariableRefImpl();
    return variableRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JarvisProjectPackage getJarvisProjectPackage()
  {
    return (JarvisProjectPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static JarvisProjectPackage getPackage()
  {
    return JarvisProjectPackage.eINSTANCE;
  }

} //JarvisProjectFactoryImpl
