/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject.impl;

import edu.upb.lp.jarvisProject.Expression;
import edu.upb.lp.jarvisProject.JarvisProjectPackage;
import edu.upb.lp.jarvisProject.Print;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.jarvisProject.impl.PrintImpl#getPrintable <em>Printable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrintImpl extends StatementImpl implements Print
{
  /**
   * The cached value of the '{@link #getPrintable() <em>Printable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrintable()
   * @generated
   * @ordered
   */
  protected Expression printable;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JarvisProjectPackage.Literals.PRINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getPrintable()
  {
    return printable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPrintable(Expression newPrintable, NotificationChain msgs)
  {
    Expression oldPrintable = printable;
    printable = newPrintable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JarvisProjectPackage.PRINT__PRINTABLE, oldPrintable, newPrintable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPrintable(Expression newPrintable)
  {
    if (newPrintable != printable)
    {
      NotificationChain msgs = null;
      if (printable != null)
        msgs = ((InternalEObject)printable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JarvisProjectPackage.PRINT__PRINTABLE, null, msgs);
      if (newPrintable != null)
        msgs = ((InternalEObject)newPrintable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JarvisProjectPackage.PRINT__PRINTABLE, null, msgs);
      msgs = basicSetPrintable(newPrintable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JarvisProjectPackage.PRINT__PRINTABLE, newPrintable, newPrintable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JarvisProjectPackage.PRINT__PRINTABLE:
        return basicSetPrintable(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JarvisProjectPackage.PRINT__PRINTABLE:
        return getPrintable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JarvisProjectPackage.PRINT__PRINTABLE:
        setPrintable((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JarvisProjectPackage.PRINT__PRINTABLE:
        setPrintable((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JarvisProjectPackage.PRINT__PRINTABLE:
        return printable != null;
    }
    return super.eIsSet(featureID);
  }

} //PrintImpl
