/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject.impl;

import edu.upb.lp.jarvisProject.JarvisProjectPackage;
import edu.upb.lp.jarvisProject.StringConcatExpression;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>String Concat Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StringConcatExpressionImpl extends ExpressionImpl implements StringConcatExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StringConcatExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JarvisProjectPackage.Literals.STRING_CONCAT_EXPRESSION;
  }

} //StringConcatExpressionImpl
