/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractJarvisProjectValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.upb.lp.jarvisProject.JarvisProjectPackage.eINSTANCE);
		return result;
	}
}
