/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class JarvisProjectGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTIMEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTOKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cHAVEKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cSOMEKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cFUNKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cWITHKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cNameAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cNameIDTerminalRuleCall_7_0 = (RuleCall)cNameAssignment_7.eContents().get(0);
		private final Assignment cFunctionsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cFunctionsFunctionParserRuleCall_8_0 = (RuleCall)cFunctionsAssignment_8.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cEvalAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cEvalExpressionParserRuleCall_10_0 = (RuleCall)cEvalAssignment_10.eContents().get(0);
		
		//Program:
		//    'JARVIS,' 'TIME' 'TO' 'HAVE' 'SOME' 'FUN' 'WITH' name=ID
		//    functions+=Function*
		//    '>' eval+=(Expression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,' 'TIME' 'TO' 'HAVE' 'SOME' 'FUN' 'WITH' name=ID
		//functions+=Function*
		//'>' eval+=(Expression)*
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'TIME'
		public Keyword getTIMEKeyword_1() { return cTIMEKeyword_1; }
		
		//'TO'
		public Keyword getTOKeyword_2() { return cTOKeyword_2; }
		
		//'HAVE'
		public Keyword getHAVEKeyword_3() { return cHAVEKeyword_3; }
		
		//'SOME'
		public Keyword getSOMEKeyword_4() { return cSOMEKeyword_4; }
		
		//'FUN'
		public Keyword getFUNKeyword_5() { return cFUNKeyword_5; }
		
		//'WITH'
		public Keyword getWITHKeyword_6() { return cWITHKeyword_6; }
		
		//name=ID
		public Assignment getNameAssignment_7() { return cNameAssignment_7; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_7_0() { return cNameIDTerminalRuleCall_7_0; }
		
		//functions+=Function*
		public Assignment getFunctionsAssignment_8() { return cFunctionsAssignment_8; }
		
		//Function
		public RuleCall getFunctionsFunctionParserRuleCall_8_0() { return cFunctionsFunctionParserRuleCall_8_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_9() { return cGreaterThanSignKeyword_9; }
		
		//eval+=(Expression)*
		public Assignment getEvalAssignment_10() { return cEvalAssignment_10; }
		
		//(Expression)
		public RuleCall getEvalExpressionParserRuleCall_10_0() { return cEvalExpressionParserRuleCall_10_0; }
	}
	public class DataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.DataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNUMBERKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cTEXTKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cBOOLEANKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//DataType:
		//    'NUMBER' | 'TEXT' | 'BOOLEAN';
		@Override public ParserRule getRule() { return rule; }
		
		//'NUMBER' | 'TEXT' | 'BOOLEAN'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'NUMBER'
		public Keyword getNUMBERKeyword_0() { return cNUMBERKeyword_0; }
		
		//'TEXT'
		public Keyword getTEXTKeyword_1() { return cTEXTKeyword_1; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANKeyword_2() { return cBOOLEANKeyword_2; }
	}
	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Function");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFunctionIntParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionStringParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFunctionBooleanParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Function:
		//    FunctionInt | FunctionString | FunctionBoolean;
		@Override public ParserRule getRule() { return rule; }
		
		//FunctionInt | FunctionString | FunctionBoolean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FunctionInt
		public RuleCall getFunctionIntParserRuleCall_0() { return cFunctionIntParserRuleCall_0; }
		
		//FunctionString
		public RuleCall getFunctionStringParserRuleCall_1() { return cFunctionStringParserRuleCall_1; }
		
		//FunctionBoolean
		public RuleCall getFunctionBooleanParserRuleCall_2() { return cFunctionBooleanParserRuleCall_2; }
	}
	public class FunctionIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.FunctionInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCREATEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPROTOCOLKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWITHKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Assignment cParamsAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final RuleCall cParamsTypedParamParserRuleCall_4_2_0_0 = (RuleCall)cParamsAssignment_4_2_0.eContents().get(0);
		private final Group cGroup_4_2_1 = (Group)cGroup_4_2.eContents().get(1);
		private final Keyword cCommaKeyword_4_2_1_0 = (Keyword)cGroup_4_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_4_2_1_1 = (Assignment)cGroup_4_2_1.eContents().get(1);
		private final RuleCall cParamsTypedParamParserRuleCall_4_2_1_1_0 = (RuleCall)cParamsAssignment_4_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatementsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatementsStatementParserRuleCall_6_0 = (RuleCall)cStatementsAssignment_6.eContents().get(0);
		private final Keyword cANDKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cSENDKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cBACKKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cReturnAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cReturnExpressionParserRuleCall_10_0 = (RuleCall)cReturnAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//FunctionInt:
		//    'JARVIS,'? 'CREATE' 'PROTOCOL' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
		//    statements+=Statement*
		//    'AND' 'SEND' 'BACK' return=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'CREATE' 'PROTOCOL' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
		//statements+=Statement*
		//'AND' 'SEND' 'BACK' return=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'CREATE'
		public Keyword getCREATEKeyword_1() { return cCREATEKeyword_1; }
		
		//'PROTOCOL'
		public Keyword getPROTOCOLKeyword_2() { return cPROTOCOLKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'WITH'
		public Keyword getWITHKeyword_4_0() { return cWITHKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//(params+=TypedParam (',' params+=TypedParam)*)?
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_4_2_0() { return cParamsAssignment_4_2_0; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_4_2_0_0() { return cParamsTypedParamParserRuleCall_4_2_0_0; }
		
		//(',' params+=TypedParam)*
		public Group getGroup_4_2_1() { return cGroup_4_2_1; }
		
		//','
		public Keyword getCommaKeyword_4_2_1_0() { return cCommaKeyword_4_2_1_0; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_4_2_1_1() { return cParamsAssignment_4_2_1_1; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_4_2_1_1_0() { return cParamsTypedParamParserRuleCall_4_2_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_3() { return cRightParenthesisKeyword_4_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//statements+=Statement*
		public Assignment getStatementsAssignment_6() { return cStatementsAssignment_6; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_6_0() { return cStatementsStatementParserRuleCall_6_0; }
		
		//'AND'
		public Keyword getANDKeyword_7() { return cANDKeyword_7; }
		
		//'SEND'
		public Keyword getSENDKeyword_8() { return cSENDKeyword_8; }
		
		//'BACK'
		public Keyword getBACKKeyword_9() { return cBACKKeyword_9; }
		
		//return=Expression
		public Assignment getReturnAssignment_10() { return cReturnAssignment_10; }
		
		//Expression
		public RuleCall getReturnExpressionParserRuleCall_10_0() { return cReturnExpressionParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class FunctionStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.FunctionString");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCREATEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFILEKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWITHKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Assignment cParamsAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final RuleCall cParamsTypedParamParserRuleCall_4_2_0_0 = (RuleCall)cParamsAssignment_4_2_0.eContents().get(0);
		private final Group cGroup_4_2_1 = (Group)cGroup_4_2.eContents().get(1);
		private final Keyword cCommaKeyword_4_2_1_0 = (Keyword)cGroup_4_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_4_2_1_1 = (Assignment)cGroup_4_2_1.eContents().get(1);
		private final RuleCall cParamsTypedParamParserRuleCall_4_2_1_1_0 = (RuleCall)cParamsAssignment_4_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatementsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatementsStatementParserRuleCall_6_0 = (RuleCall)cStatementsAssignment_6.eContents().get(0);
		private final Keyword cANDKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cSENDKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cBACKKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cReturnAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cReturnExpressionParserRuleCall_10_0 = (RuleCall)cReturnAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//FunctionString:
		//    'JARVIS,'? 'CREATE' 'FILE' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
		//    statements+=Statement*
		//    'AND' 'SEND' 'BACK' return=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'CREATE' 'FILE' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
		//statements+=Statement*
		//'AND' 'SEND' 'BACK' return=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'CREATE'
		public Keyword getCREATEKeyword_1() { return cCREATEKeyword_1; }
		
		//'FILE'
		public Keyword getFILEKeyword_2() { return cFILEKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'WITH'
		public Keyword getWITHKeyword_4_0() { return cWITHKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//(params+=TypedParam (',' params+=TypedParam)*)?
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_4_2_0() { return cParamsAssignment_4_2_0; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_4_2_0_0() { return cParamsTypedParamParserRuleCall_4_2_0_0; }
		
		//(',' params+=TypedParam)*
		public Group getGroup_4_2_1() { return cGroup_4_2_1; }
		
		//','
		public Keyword getCommaKeyword_4_2_1_0() { return cCommaKeyword_4_2_1_0; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_4_2_1_1() { return cParamsAssignment_4_2_1_1; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_4_2_1_1_0() { return cParamsTypedParamParserRuleCall_4_2_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_3() { return cRightParenthesisKeyword_4_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//statements+=Statement*
		public Assignment getStatementsAssignment_6() { return cStatementsAssignment_6; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_6_0() { return cStatementsStatementParserRuleCall_6_0; }
		
		//'AND'
		public Keyword getANDKeyword_7() { return cANDKeyword_7; }
		
		//'SEND'
		public Keyword getSENDKeyword_8() { return cSENDKeyword_8; }
		
		//'BACK'
		public Keyword getBACKKeyword_9() { return cBACKKeyword_9; }
		
		//return=Expression
		public Assignment getReturnAssignment_10() { return cReturnAssignment_10; }
		
		//Expression
		public RuleCall getReturnExpressionParserRuleCall_10_0() { return cReturnExpressionParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class FunctionBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.FunctionBoolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCREATEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAUTOMATONKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWITHKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Assignment cParamsAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final RuleCall cParamsTypedParamParserRuleCall_4_2_0_0 = (RuleCall)cParamsAssignment_4_2_0.eContents().get(0);
		private final Group cGroup_4_2_1 = (Group)cGroup_4_2.eContents().get(1);
		private final Keyword cCommaKeyword_4_2_1_0 = (Keyword)cGroup_4_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_4_2_1_1 = (Assignment)cGroup_4_2_1.eContents().get(1);
		private final RuleCall cParamsTypedParamParserRuleCall_4_2_1_1_0 = (RuleCall)cParamsAssignment_4_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatementsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatementsStatementParserRuleCall_6_0 = (RuleCall)cStatementsAssignment_6.eContents().get(0);
		private final Keyword cANDKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cSENDKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cBACKKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cReturnAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cReturnExpressionParserRuleCall_10_0 = (RuleCall)cReturnAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//FunctionBoolean:
		//    'JARVIS,'? 'CREATE' 'AUTOMATON' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
		//    statements+=Statement*
		//    'AND' 'SEND' 'BACK' return=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'CREATE' 'AUTOMATON' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
		//statements+=Statement*
		//'AND' 'SEND' 'BACK' return=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'CREATE'
		public Keyword getCREATEKeyword_1() { return cCREATEKeyword_1; }
		
		//'AUTOMATON'
		public Keyword getAUTOMATONKeyword_2() { return cAUTOMATONKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'WITH'
		public Keyword getWITHKeyword_4_0() { return cWITHKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//(params+=TypedParam (',' params+=TypedParam)*)?
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_4_2_0() { return cParamsAssignment_4_2_0; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_4_2_0_0() { return cParamsTypedParamParserRuleCall_4_2_0_0; }
		
		//(',' params+=TypedParam)*
		public Group getGroup_4_2_1() { return cGroup_4_2_1; }
		
		//','
		public Keyword getCommaKeyword_4_2_1_0() { return cCommaKeyword_4_2_1_0; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_4_2_1_1() { return cParamsAssignment_4_2_1_1; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_4_2_1_1_0() { return cParamsTypedParamParserRuleCall_4_2_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_3() { return cRightParenthesisKeyword_4_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//statements+=Statement*
		public Assignment getStatementsAssignment_6() { return cStatementsAssignment_6; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_6_0() { return cStatementsStatementParserRuleCall_6_0; }
		
		//'AND'
		public Keyword getANDKeyword_7() { return cANDKeyword_7; }
		
		//'SEND'
		public Keyword getSENDKeyword_8() { return cSENDKeyword_8; }
		
		//'BACK'
		public Keyword getBACKKeyword_9() { return cBACKKeyword_9; }
		
		//return=Expression
		public Assignment getReturnAssignment_10() { return cReturnAssignment_10; }
		
		//Expression
		public RuleCall getReturnExpressionParserRuleCall_10_0() { return cReturnExpressionParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class TypedParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.TypedParam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeDataTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//TypedParam:
		//    type=DataType name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//type=DataType name=ID
		public Group getGroup() { return cGroup; }
		
		//type=DataType
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//DataType
		public RuleCall getTypeDataTypeParserRuleCall_0_0() { return cTypeDataTypeParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInitializationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAssignmentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPrintParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cWhileParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cIfParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cIppParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cImmParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Statement:
		//    Initialization | Assignment | Print | While | If | Ipp | Imm;
		@Override public ParserRule getRule() { return rule; }
		
		//Initialization | Assignment | Print | While | If | Ipp | Imm
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Initialization
		public RuleCall getInitializationParserRuleCall_0() { return cInitializationParserRuleCall_0; }
		
		//Assignment
		public RuleCall getAssignmentParserRuleCall_1() { return cAssignmentParserRuleCall_1; }
		
		//Print
		public RuleCall getPrintParserRuleCall_2() { return cPrintParserRuleCall_2; }
		
		//While
		public RuleCall getWhileParserRuleCall_3() { return cWhileParserRuleCall_3; }
		
		//If
		public RuleCall getIfParserRuleCall_4() { return cIfParserRuleCall_4; }
		
		//Ipp
		public RuleCall getIppParserRuleCall_5() { return cIppParserRuleCall_5; }
		
		//Imm
		public RuleCall getImmParserRuleCall_6() { return cImmParserRuleCall_6; }
	}
	public class InitializationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Initialization");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSETKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeDataTypeParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		private final Assignment cVarAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVarIDTerminalRuleCall_3_0 = (RuleCall)cVarAssignment_3.eContents().get(0);
		private final Keyword cASKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueExpressionParserRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		
		//Initialization:
		//    'JARVIS,'? 'SET' type=DataType var=ID 'AS' value=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'SET' type=DataType var=ID 'AS' value=Expression
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'SET'
		public Keyword getSETKeyword_1() { return cSETKeyword_1; }
		
		//type=DataType
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//DataType
		public RuleCall getTypeDataTypeParserRuleCall_2_0() { return cTypeDataTypeParserRuleCall_2_0; }
		
		//var=ID
		public Assignment getVarAssignment_3() { return cVarAssignment_3; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_3_0() { return cVarIDTerminalRuleCall_3_0; }
		
		//'AS'
		public Keyword getASKeyword_4() { return cASKeyword_4; }
		
		//value=Expression
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_5_0() { return cValueExpressionParserRuleCall_5_0; }
	}
	public class AssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Assignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNOWKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSETKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVarAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVarIDTerminalRuleCall_3_0 = (RuleCall)cVarAssignment_3.eContents().get(0);
		private final Keyword cASKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueExpressionParserRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		
		//Assignment:
		//    'JARVIS,'? 'NOW' 'SET' var=ID 'AS' value=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'NOW' 'SET' var=ID 'AS' value=Expression
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'NOW'
		public Keyword getNOWKeyword_1() { return cNOWKeyword_1; }
		
		//'SET'
		public Keyword getSETKeyword_2() { return cSETKeyword_2; }
		
		//var=ID
		public Assignment getVarAssignment_3() { return cVarAssignment_3; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_3_0() { return cVarIDTerminalRuleCall_3_0; }
		
		//'AS'
		public Keyword getASKeyword_4() { return cASKeyword_4; }
		
		//value=Expression
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_5_0() { return cValueExpressionParserRuleCall_5_0; }
	}
	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSHOWKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPrintableAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPrintableExpressionParserRuleCall_3_0 = (RuleCall)cPrintableAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Print:
		//    'JARVIS,'? 'SHOW' '(' printable=Expression ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'SHOW' '(' printable=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'SHOW'
		public Keyword getSHOWKeyword_1() { return cSHOWKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//printable=Expression
		public Assignment getPrintableAssignment_3() { return cPrintableAssignment_3; }
		
		//Expression
		public RuleCall getPrintableExpressionParserRuleCall_3_0() { return cPrintableExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class WhileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.While");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLOOPKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWHILEKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cConditionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConditionExpressionParserRuleCall_4_0 = (RuleCall)cConditionAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStatementsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStatementsStatementParserRuleCall_7_0 = (RuleCall)cStatementsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//While:
		//    'JARVIS,'? 'LOOP' 'WHILE' '(' condition=Expression ')' '{' statements+=Statement+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'LOOP' 'WHILE' '(' condition=Expression ')' '{' statements+=Statement+ '}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'LOOP'
		public Keyword getLOOPKeyword_1() { return cLOOPKeyword_1; }
		
		//'WHILE'
		public Keyword getWHILEKeyword_2() { return cWHILEKeyword_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//condition=Expression
		public Assignment getConditionAssignment_4() { return cConditionAssignment_4; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_4_0() { return cConditionExpressionParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//statements+=Statement+
		public Assignment getStatementsAssignment_7() { return cStatementsAssignment_7; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_7_0() { return cStatementsStatementParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class IfElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.If");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTRYKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionExpressionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatementsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatementsStatementParserRuleCall_6_0 = (RuleCall)cStatementsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//If:
		//    'JARVIS,'? 'TRY' '(' condition=Expression ')' '{' statements+=Statement+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'TRY' '(' condition=Expression ')' '{' statements+=Statement+ '}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'TRY'
		public Keyword getTRYKeyword_1() { return cTRYKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//condition=Expression
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//Expression
		public RuleCall getConditionExpressionParserRuleCall_3_0() { return cConditionExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//statements+=Statement+
		public Assignment getStatementsAssignment_6() { return cStatementsAssignment_6; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_6_0() { return cStatementsStatementParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class IppElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Ipp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cBUMPKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarIDTerminalRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		
		//Ipp:
		//    'JARVIS,'? 'BUMP' var=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'BUMP' var=ID
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'BUMP'
		public Keyword getBUMPKeyword_1() { return cBUMPKeyword_1; }
		
		//var=ID
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_2_0() { return cVarIDTerminalRuleCall_2_0; }
	}
	public class ImmElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Imm");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDROPKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarIDTerminalRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		
		//Imm:
		//    'JARVIS,'? 'DROP' var=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'DROP' var=ID
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'DROP'
		public Keyword getDROPKeyword_1() { return cDROPKeyword_1; }
		
		//var=ID
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_2_0() { return cVarIDTerminalRuleCall_2_0; }
	}
	public class IntValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntValue");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//IntValue:
		//    val=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//val=INT
		public Assignment getValAssignment() { return cValAssignment; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_0() { return cValINTTerminalRuleCall_0; }
	}
	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.StringValue");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValSTRINGTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//StringValue:
		//    val=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//val=STRING
		public Assignment getValAssignment() { return cValAssignment; }
		
		//STRING
		public RuleCall getValSTRINGTerminalRuleCall_0() { return cValSTRINGTerminalRuleCall_0; }
	}
	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cValTRUEKeyword_0_0 = (Keyword)cValAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cBooleanValueAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cFALSEKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//BooleanValue:
		//    val?='TRUE' | {BooleanValue} 'FALSE';
		@Override public ParserRule getRule() { return rule; }
		
		//val?='TRUE' | {BooleanValue} 'FALSE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//val?='TRUE'
		public Assignment getValAssignment_0() { return cValAssignment_0; }
		
		//'TRUE'
		public Keyword getValTRUEKeyword_0_0() { return cValTRUEKeyword_0_0; }
		
		//{BooleanValue} 'FALSE'
		public Group getGroup_1() { return cGroup_1; }
		
		//{BooleanValue}
		public Action getBooleanValueAction_1_0() { return cBooleanValueAction_1_0; }
		
		//'FALSE'
		public Keyword getFALSEKeyword_1_1() { return cFALSEKeyword_1_1; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Expression");
		private final RuleCall cOrExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Expression returns Expression:
		//    OrExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//OrExpression
		public RuleCall getOrExpressionParserRuleCall() { return cOrExpressionParserRuleCall; }
	}
	public class OrExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.OrExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OrExpression returns Expression:
		//    AndExpression ({OrExpression.left=current} 'OR' right=AndExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//AndExpression ({OrExpression.left=current} 'OR' right=AndExpression)*
		public Group getGroup() { return cGroup; }
		
		//AndExpression
		public RuleCall getAndExpressionParserRuleCall_0() { return cAndExpressionParserRuleCall_0; }
		
		//({OrExpression.left=current} 'OR' right=AndExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{OrExpression.left=current}
		public Action getOrExpressionLeftAction_1_0() { return cOrExpressionLeftAction_1_0; }
		
		//'OR'
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }
		
		//right=AndExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AndExpression
		public RuleCall getRightAndExpressionParserRuleCall_1_2_0() { return cRightAndExpressionParserRuleCall_1_2_0; }
	}
	public class AndExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.AndExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cEqualityExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightEqualityExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AndExpression returns Expression:
		//    EqualityExpression ({AndExpression.left=current} 'AND' right=EqualityExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//EqualityExpression ({AndExpression.left=current} 'AND' right=EqualityExpression)*
		public Group getGroup() { return cGroup; }
		
		//EqualityExpression
		public RuleCall getEqualityExpressionParserRuleCall_0() { return cEqualityExpressionParserRuleCall_0; }
		
		//({AndExpression.left=current} 'AND' right=EqualityExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{AndExpression.left=current}
		public Action getAndExpressionLeftAction_1_0() { return cAndExpressionLeftAction_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }
		
		//right=EqualityExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//EqualityExpression
		public RuleCall getRightEqualityExpressionParserRuleCall_1_2_0() { return cRightEqualityExpressionParserRuleCall_1_2_0; }
	}
	public class EqualityExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.EqualityExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cComparisonExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cEqualityExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpEqualsSignEqualsSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpExclamationMarkEqualsSignKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightComparisonExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//EqualityExpression returns Expression:
		//    ComparisonExpression ({EqualityExpression.left=current} op=('==' | '!=') right=ComparisonExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ComparisonExpression ({EqualityExpression.left=current} op=('==' | '!=') right=ComparisonExpression)*
		public Group getGroup() { return cGroup; }
		
		//ComparisonExpression
		public RuleCall getComparisonExpressionParserRuleCall_0() { return cComparisonExpressionParserRuleCall_0; }
		
		//({EqualityExpression.left=current} op=('==' | '!=') right=ComparisonExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{EqualityExpression.left=current}
		public Action getEqualityExpressionLeftAction_1_0() { return cEqualityExpressionLeftAction_1_0; }
		
		//op=('==' | '!=')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('==' | '!=')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'=='
		public Keyword getOpEqualsSignEqualsSignKeyword_1_1_0_0() { return cOpEqualsSignEqualsSignKeyword_1_1_0_0; }
		
		//'!='
		public Keyword getOpExclamationMarkEqualsSignKeyword_1_1_0_1() { return cOpExclamationMarkEqualsSignKeyword_1_1_0_1; }
		
		//right=ComparisonExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//ComparisonExpression
		public RuleCall getRightComparisonExpressionParserRuleCall_1_2_0() { return cRightComparisonExpressionParserRuleCall_1_2_0; }
	}
	public class ComparisonExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.ComparisonExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAdditiveExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cComparisonExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpLessThanSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpGreaterThanSignKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Keyword cOpLessThanSignEqualsSignKeyword_1_1_0_2 = (Keyword)cOpAlternatives_1_1_0.eContents().get(2);
		private final Keyword cOpGreaterThanSignEqualsSignKeyword_1_1_0_3 = (Keyword)cOpAlternatives_1_1_0.eContents().get(3);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAdditiveExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ComparisonExpression returns Expression:
		//    AdditiveExpression ({ComparisonExpression.left=current} op=('<' | '>' | '<=' | '>=') right=AdditiveExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//AdditiveExpression ({ComparisonExpression.left=current} op=('<' | '>' | '<=' | '>=') right=AdditiveExpression)*
		public Group getGroup() { return cGroup; }
		
		//AdditiveExpression
		public RuleCall getAdditiveExpressionParserRuleCall_0() { return cAdditiveExpressionParserRuleCall_0; }
		
		//({ComparisonExpression.left=current} op=('<' | '>' | '<=' | '>=') right=AdditiveExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{ComparisonExpression.left=current}
		public Action getComparisonExpressionLeftAction_1_0() { return cComparisonExpressionLeftAction_1_0; }
		
		//op=('<' | '>' | '<=' | '>=')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('<' | '>' | '<=' | '>=')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'<'
		public Keyword getOpLessThanSignKeyword_1_1_0_0() { return cOpLessThanSignKeyword_1_1_0_0; }
		
		//'>'
		public Keyword getOpGreaterThanSignKeyword_1_1_0_1() { return cOpGreaterThanSignKeyword_1_1_0_1; }
		
		//'<='
		public Keyword getOpLessThanSignEqualsSignKeyword_1_1_0_2() { return cOpLessThanSignEqualsSignKeyword_1_1_0_2; }
		
		//'>='
		public Keyword getOpGreaterThanSignEqualsSignKeyword_1_1_0_3() { return cOpGreaterThanSignEqualsSignKeyword_1_1_0_3; }
		
		//right=AdditiveExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AdditiveExpression
		public RuleCall getRightAdditiveExpressionParserRuleCall_1_2_0() { return cRightAdditiveExpressionParserRuleCall_1_2_0; }
	}
	public class AdditiveExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.AdditiveExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicativeExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAdditiveExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpPlusSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpHyphenMinusKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightMultiplicativeExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AdditiveExpression returns Expression:
		//    MultiplicativeExpression ({AdditiveExpression.left=current} op=('+' | '-') right=MultiplicativeExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//MultiplicativeExpression ({AdditiveExpression.left=current} op=('+' | '-') right=MultiplicativeExpression)*
		public Group getGroup() { return cGroup; }
		
		//MultiplicativeExpression
		public RuleCall getMultiplicativeExpressionParserRuleCall_0() { return cMultiplicativeExpressionParserRuleCall_0; }
		
		//({AdditiveExpression.left=current} op=('+' | '-') right=MultiplicativeExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{AdditiveExpression.left=current}
		public Action getAdditiveExpressionLeftAction_1_0() { return cAdditiveExpressionLeftAction_1_0; }
		
		//op=('+' | '-')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('+' | '-')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'+'
		public Keyword getOpPlusSignKeyword_1_1_0_0() { return cOpPlusSignKeyword_1_1_0_0; }
		
		//'-'
		public Keyword getOpHyphenMinusKeyword_1_1_0_1() { return cOpHyphenMinusKeyword_1_1_0_1; }
		
		//right=MultiplicativeExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//MultiplicativeExpression
		public RuleCall getRightMultiplicativeExpressionParserRuleCall_1_2_0() { return cRightMultiplicativeExpressionParserRuleCall_1_2_0; }
	}
	public class MultiplicativeExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.MultiplicativeExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cMultiplicativeExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpAsteriskKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpSolidusKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Keyword cOpPercentSignKeyword_1_1_0_2 = (Keyword)cOpAlternatives_1_1_0.eContents().get(2);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//MultiplicativeExpression returns Expression:
		//    PrimaryExpression ({MultiplicativeExpression.left=current} op=('*' | '/' | '%') right=PrimaryExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//PrimaryExpression ({MultiplicativeExpression.left=current} op=('*' | '/' | '%') right=PrimaryExpression)*
		public Group getGroup() { return cGroup; }
		
		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_0() { return cPrimaryExpressionParserRuleCall_0; }
		
		//({MultiplicativeExpression.left=current} op=('*' | '/' | '%') right=PrimaryExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{MultiplicativeExpression.left=current}
		public Action getMultiplicativeExpressionLeftAction_1_0() { return cMultiplicativeExpressionLeftAction_1_0; }
		
		//op=('*' | '/' | '%')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('*' | '/' | '%')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'*'
		public Keyword getOpAsteriskKeyword_1_1_0_0() { return cOpAsteriskKeyword_1_1_0_0; }
		
		//'/'
		public Keyword getOpSolidusKeyword_1_1_0_1() { return cOpSolidusKeyword_1_1_0_1; }
		
		//'%'
		public Keyword getOpPercentSignKeyword_1_1_0_2() { return cOpPercentSignKeyword_1_1_0_2; }
		
		//right=PrimaryExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//PrimaryExpression
		public RuleCall getRightPrimaryExpressionParserRuleCall_1_2_0() { return cRightPrimaryExpressionParserRuleCall_1_2_0; }
	}
	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringValueParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBooleanValueParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFunctionCallParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cVariableRefParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final RuleCall cExpressionParserRuleCall_5_1 = (RuleCall)cGroup_5.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		
		//PrimaryExpression returns Expression:
		//    IntValue
		//    | StringValue
		//    | BooleanValue
		//    | FunctionCall
		//    | VariableRef
		//    | '(' Expression ')';
		@Override public ParserRule getRule() { return rule; }
		
		//IntValue
		//| StringValue
		//| BooleanValue
		//| FunctionCall
		//| VariableRef
		//| '(' Expression ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntValue
		public RuleCall getIntValueParserRuleCall_0() { return cIntValueParserRuleCall_0; }
		
		//StringValue
		public RuleCall getStringValueParserRuleCall_1() { return cStringValueParserRuleCall_1; }
		
		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_2() { return cBooleanValueParserRuleCall_2; }
		
		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_3() { return cFunctionCallParserRuleCall_3; }
		
		//VariableRef
		public RuleCall getVariableRefParserRuleCall_4() { return cVariableRefParserRuleCall_4; }
		
		//'(' Expression ')'
		public Group getGroup_5() { return cGroup_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }
		
		//Expression
		public RuleCall getExpressionParserRuleCall_5_1() { return cExpressionParserRuleCall_5_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_2() { return cRightParenthesisKeyword_5_2; }
	}
	public class VariableRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.VariableRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//VariableRef returns Expression:
		//    {VariableRef} var=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{VariableRef} var=ID
		public Group getGroup() { return cGroup; }
		
		//{VariableRef}
		public Action getVariableRefAction_0() { return cVariableRefAction_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.FunctionCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cRUNKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPROTOCOLKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFunctionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cFunctionFunctionCrossReference_3_0 = (CrossReference)cFunctionAssignment_3.eContents().get(0);
		private final RuleCall cFunctionFunctionIDTerminalRuleCall_3_0_1 = (RuleCall)cFunctionFunctionCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cWITHKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_4_2 = (Group)cGroup_4.eContents().get(2);
		private final Assignment cArgsAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final RuleCall cArgsExpressionParserRuleCall_4_2_0_0 = (RuleCall)cArgsAssignment_4_2_0.eContents().get(0);
		private final Group cGroup_4_2_1 = (Group)cGroup_4_2.eContents().get(1);
		private final Keyword cCommaKeyword_4_2_1_0 = (Keyword)cGroup_4_2_1.eContents().get(0);
		private final Assignment cArgsAssignment_4_2_1_1 = (Assignment)cGroup_4_2_1.eContents().get(1);
		private final RuleCall cArgsExpressionParserRuleCall_4_2_1_1_0 = (RuleCall)cArgsAssignment_4_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		
		//FunctionCall:
		//    'JARVIS,'? 'RUN' 'PROTOCOL' function=[Function] ('WITH' '(' (args+=Expression (',' args+=Expression)*)? ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,'? 'RUN' 'PROTOCOL' function=[Function] ('WITH' '(' (args+=Expression (',' args+=Expression)*)? ')')?
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'?
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'RUN'
		public Keyword getRUNKeyword_1() { return cRUNKeyword_1; }
		
		//'PROTOCOL'
		public Keyword getPROTOCOLKeyword_2() { return cPROTOCOLKeyword_2; }
		
		//function=[Function]
		public Assignment getFunctionAssignment_3() { return cFunctionAssignment_3; }
		
		//[Function]
		public CrossReference getFunctionFunctionCrossReference_3_0() { return cFunctionFunctionCrossReference_3_0; }
		
		//ID
		public RuleCall getFunctionFunctionIDTerminalRuleCall_3_0_1() { return cFunctionFunctionIDTerminalRuleCall_3_0_1; }
		
		//('WITH' '(' (args+=Expression (',' args+=Expression)*)? ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'WITH'
		public Keyword getWITHKeyword_4_0() { return cWITHKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//(args+=Expression (',' args+=Expression)*)?
		public Group getGroup_4_2() { return cGroup_4_2; }
		
		//args+=Expression
		public Assignment getArgsAssignment_4_2_0() { return cArgsAssignment_4_2_0; }
		
		//Expression
		public RuleCall getArgsExpressionParserRuleCall_4_2_0_0() { return cArgsExpressionParserRuleCall_4_2_0_0; }
		
		//(',' args+=Expression)*
		public Group getGroup_4_2_1() { return cGroup_4_2_1; }
		
		//','
		public Keyword getCommaKeyword_4_2_1_0() { return cCommaKeyword_4_2_1_0; }
		
		//args+=Expression
		public Assignment getArgsAssignment_4_2_1_1() { return cArgsAssignment_4_2_1_1; }
		
		//Expression
		public RuleCall getArgsExpressionParserRuleCall_4_2_1_1_0() { return cArgsExpressionParserRuleCall_4_2_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_3() { return cRightParenthesisKeyword_4_3; }
	}
	
	
	private final ProgramElements pProgram;
	private final DataTypeElements pDataType;
	private final FunctionElements pFunction;
	private final FunctionIntElements pFunctionInt;
	private final FunctionStringElements pFunctionString;
	private final FunctionBooleanElements pFunctionBoolean;
	private final TypedParamElements pTypedParam;
	private final StatementElements pStatement;
	private final InitializationElements pInitialization;
	private final AssignmentElements pAssignment;
	private final PrintElements pPrint;
	private final WhileElements pWhile;
	private final IfElements pIf;
	private final IppElements pIpp;
	private final ImmElements pImm;
	private final IntValueElements pIntValue;
	private final StringValueElements pStringValue;
	private final BooleanValueElements pBooleanValue;
	private final ExpressionElements pExpression;
	private final OrExpressionElements pOrExpression;
	private final AndExpressionElements pAndExpression;
	private final EqualityExpressionElements pEqualityExpression;
	private final ComparisonExpressionElements pComparisonExpression;
	private final AdditiveExpressionElements pAdditiveExpression;
	private final MultiplicativeExpressionElements pMultiplicativeExpression;
	private final PrimaryExpressionElements pPrimaryExpression;
	private final VariableRefElements pVariableRef;
	private final FunctionCallElements pFunctionCall;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public JarvisProjectGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pDataType = new DataTypeElements();
		this.pFunction = new FunctionElements();
		this.pFunctionInt = new FunctionIntElements();
		this.pFunctionString = new FunctionStringElements();
		this.pFunctionBoolean = new FunctionBooleanElements();
		this.pTypedParam = new TypedParamElements();
		this.pStatement = new StatementElements();
		this.pInitialization = new InitializationElements();
		this.pAssignment = new AssignmentElements();
		this.pPrint = new PrintElements();
		this.pWhile = new WhileElements();
		this.pIf = new IfElements();
		this.pIpp = new IppElements();
		this.pImm = new ImmElements();
		this.pIntValue = new IntValueElements();
		this.pStringValue = new StringValueElements();
		this.pBooleanValue = new BooleanValueElements();
		this.pExpression = new ExpressionElements();
		this.pOrExpression = new OrExpressionElements();
		this.pAndExpression = new AndExpressionElements();
		this.pEqualityExpression = new EqualityExpressionElements();
		this.pComparisonExpression = new ComparisonExpressionElements();
		this.pAdditiveExpression = new AdditiveExpressionElements();
		this.pMultiplicativeExpression = new MultiplicativeExpressionElements();
		this.pPrimaryExpression = new PrimaryExpressionElements();
		this.pVariableRef = new VariableRefElements();
		this.pFunctionCall = new FunctionCallElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("edu.upb.lp.JarvisProject".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//    'JARVIS,' 'TIME' 'TO' 'HAVE' 'SOME' 'FUN' 'WITH' name=ID
	//    functions+=Function*
	//    '>' eval+=(Expression)*;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//DataType:
	//    'NUMBER' | 'TEXT' | 'BOOLEAN';
	public DataTypeElements getDataTypeAccess() {
		return pDataType;
	}
	
	public ParserRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//Function:
	//    FunctionInt | FunctionString | FunctionBoolean;
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//FunctionInt:
	//    'JARVIS,'? 'CREATE' 'PROTOCOL' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
	//    statements+=Statement*
	//    'AND' 'SEND' 'BACK' return=Expression
	//    '}';
	public FunctionIntElements getFunctionIntAccess() {
		return pFunctionInt;
	}
	
	public ParserRule getFunctionIntRule() {
		return getFunctionIntAccess().getRule();
	}
	
	//FunctionString:
	//    'JARVIS,'? 'CREATE' 'FILE' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
	//    statements+=Statement*
	//    'AND' 'SEND' 'BACK' return=Expression
	//    '}';
	public FunctionStringElements getFunctionStringAccess() {
		return pFunctionString;
	}
	
	public ParserRule getFunctionStringRule() {
		return getFunctionStringAccess().getRule();
	}
	
	//FunctionBoolean:
	//    'JARVIS,'? 'CREATE' 'AUTOMATON' name=ID ('WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')')? '{'
	//    statements+=Statement*
	//    'AND' 'SEND' 'BACK' return=Expression
	//    '}';
	public FunctionBooleanElements getFunctionBooleanAccess() {
		return pFunctionBoolean;
	}
	
	public ParserRule getFunctionBooleanRule() {
		return getFunctionBooleanAccess().getRule();
	}
	
	//TypedParam:
	//    type=DataType name=ID;
	public TypedParamElements getTypedParamAccess() {
		return pTypedParam;
	}
	
	public ParserRule getTypedParamRule() {
		return getTypedParamAccess().getRule();
	}
	
	//Statement:
	//    Initialization | Assignment | Print | While | If | Ipp | Imm;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Initialization:
	//    'JARVIS,'? 'SET' type=DataType var=ID 'AS' value=Expression;
	public InitializationElements getInitializationAccess() {
		return pInitialization;
	}
	
	public ParserRule getInitializationRule() {
		return getInitializationAccess().getRule();
	}
	
	//Assignment:
	//    'JARVIS,'? 'NOW' 'SET' var=ID 'AS' value=Expression;
	public AssignmentElements getAssignmentAccess() {
		return pAssignment;
	}
	
	public ParserRule getAssignmentRule() {
		return getAssignmentAccess().getRule();
	}
	
	//Print:
	//    'JARVIS,'? 'SHOW' '(' printable=Expression ')';
	public PrintElements getPrintAccess() {
		return pPrint;
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}
	
	//While:
	//    'JARVIS,'? 'LOOP' 'WHILE' '(' condition=Expression ')' '{' statements+=Statement+ '}';
	public WhileElements getWhileAccess() {
		return pWhile;
	}
	
	public ParserRule getWhileRule() {
		return getWhileAccess().getRule();
	}
	
	//If:
	//    'JARVIS,'? 'TRY' '(' condition=Expression ')' '{' statements+=Statement+ '}';
	public IfElements getIfAccess() {
		return pIf;
	}
	
	public ParserRule getIfRule() {
		return getIfAccess().getRule();
	}
	
	//Ipp:
	//    'JARVIS,'? 'BUMP' var=ID;
	public IppElements getIppAccess() {
		return pIpp;
	}
	
	public ParserRule getIppRule() {
		return getIppAccess().getRule();
	}
	
	//Imm:
	//    'JARVIS,'? 'DROP' var=ID;
	public ImmElements getImmAccess() {
		return pImm;
	}
	
	public ParserRule getImmRule() {
		return getImmAccess().getRule();
	}
	
	//IntValue:
	//    val=INT;
	public IntValueElements getIntValueAccess() {
		return pIntValue;
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}
	
	//StringValue:
	//    val=STRING;
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}
	
	//BooleanValue:
	//    val?='TRUE' | {BooleanValue} 'FALSE';
	public BooleanValueElements getBooleanValueAccess() {
		return pBooleanValue;
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//Expression returns Expression:
	//    OrExpression;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//OrExpression returns Expression:
	//    AndExpression ({OrExpression.left=current} 'OR' right=AndExpression)*;
	public OrExpressionElements getOrExpressionAccess() {
		return pOrExpression;
	}
	
	public ParserRule getOrExpressionRule() {
		return getOrExpressionAccess().getRule();
	}
	
	//AndExpression returns Expression:
	//    EqualityExpression ({AndExpression.left=current} 'AND' right=EqualityExpression)*;
	public AndExpressionElements getAndExpressionAccess() {
		return pAndExpression;
	}
	
	public ParserRule getAndExpressionRule() {
		return getAndExpressionAccess().getRule();
	}
	
	//EqualityExpression returns Expression:
	//    ComparisonExpression ({EqualityExpression.left=current} op=('==' | '!=') right=ComparisonExpression)*;
	public EqualityExpressionElements getEqualityExpressionAccess() {
		return pEqualityExpression;
	}
	
	public ParserRule getEqualityExpressionRule() {
		return getEqualityExpressionAccess().getRule();
	}
	
	//ComparisonExpression returns Expression:
	//    AdditiveExpression ({ComparisonExpression.left=current} op=('<' | '>' | '<=' | '>=') right=AdditiveExpression)*;
	public ComparisonExpressionElements getComparisonExpressionAccess() {
		return pComparisonExpression;
	}
	
	public ParserRule getComparisonExpressionRule() {
		return getComparisonExpressionAccess().getRule();
	}
	
	//AdditiveExpression returns Expression:
	//    MultiplicativeExpression ({AdditiveExpression.left=current} op=('+' | '-') right=MultiplicativeExpression)*;
	public AdditiveExpressionElements getAdditiveExpressionAccess() {
		return pAdditiveExpression;
	}
	
	public ParserRule getAdditiveExpressionRule() {
		return getAdditiveExpressionAccess().getRule();
	}
	
	//MultiplicativeExpression returns Expression:
	//    PrimaryExpression ({MultiplicativeExpression.left=current} op=('*' | '/' | '%') right=PrimaryExpression)*;
	public MultiplicativeExpressionElements getMultiplicativeExpressionAccess() {
		return pMultiplicativeExpression;
	}
	
	public ParserRule getMultiplicativeExpressionRule() {
		return getMultiplicativeExpressionAccess().getRule();
	}
	
	//PrimaryExpression returns Expression:
	//    IntValue
	//    | StringValue
	//    | BooleanValue
	//    | FunctionCall
	//    | VariableRef
	//    | '(' Expression ')';
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return pPrimaryExpression;
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}
	
	//VariableRef returns Expression:
	//    {VariableRef} var=ID;
	public VariableRefElements getVariableRefAccess() {
		return pVariableRef;
	}
	
	public ParserRule getVariableRefRule() {
		return getVariableRefAccess().getRule();
	}
	
	//FunctionCall:
	//    'JARVIS,'? 'RUN' 'PROTOCOL' function=[Function] ('WITH' '(' (args+=Expression (',' args+=Expression)*)? ')')?;
	public FunctionCallElements getFunctionCallAccess() {
		return pFunctionCall;
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
