/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class JarvisProjectGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cFunctionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFunctionsFunctionParserRuleCall_1_0 = (RuleCall)cFunctionsAssignment_1.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEvalAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEvalExpressionParserRuleCall_3_0 = (RuleCall)cEvalAssignment_3.eContents().get(0);
		
		//Program:
		//    name=ID
		//    functions+=Function*
		//    '>' eval+=Expression*;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		//functions+=Function*
		//'>' eval+=Expression*
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//functions+=Function*
		public Assignment getFunctionsAssignment_1() { return cFunctionsAssignment_1; }
		
		//Function
		public RuleCall getFunctionsFunctionParserRuleCall_1_0() { return cFunctionsFunctionParserRuleCall_1_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_2() { return cGreaterThanSignKeyword_2; }
		
		//eval+=Expression*
		public Assignment getEvalAssignment_3() { return cEvalAssignment_3; }
		
		//Expression
		public RuleCall getEvalExpressionParserRuleCall_3_0() { return cEvalExpressionParserRuleCall_3_0; }
	}
	public class DataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.DataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cINTKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSTRINGKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cBOOLEANKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//DataType:
		//    'INT' | 'STRING' | 'BOOLEAN';
		@Override public ParserRule getRule() { return rule; }
		
		//'INT' | 'STRING' | 'BOOLEAN'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'INT'
		public Keyword getINTKeyword_0() { return cINTKeyword_0; }
		
		//'STRING'
		public Keyword getSTRINGKeyword_1() { return cSTRINGKeyword_1; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANKeyword_2() { return cBOOLEANKeyword_2; }
	}
	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCREATEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPROTOCOLKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeDataTypeParserRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cWITHKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cParamsAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cParamsTypedParamParserRuleCall_7_0_0 = (RuleCall)cParamsAssignment_7_0.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cCommaKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cParamsAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final RuleCall cParamsTypedParamParserRuleCall_7_1_1_0 = (RuleCall)cParamsAssignment_7_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cStatementsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cStatementsStatementParserRuleCall_10_0 = (RuleCall)cStatementsAssignment_10.eContents().get(0);
		private final Keyword cRETURNKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cReturnAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cReturnExpressionParserRuleCall_12_0 = (RuleCall)cReturnAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Function:
		//    'JARVIS,' 'CREATE' 'PROTOCOL' type=DataType name=ID
		//    'WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')' '{'
		//        statements+=Statement*
		//        'RETURN' return=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,' 'CREATE' 'PROTOCOL' type=DataType name=ID
		//'WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')' '{'
		//    statements+=Statement*
		//    'RETURN' return=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'CREATE'
		public Keyword getCREATEKeyword_1() { return cCREATEKeyword_1; }
		
		//'PROTOCOL'
		public Keyword getPROTOCOLKeyword_2() { return cPROTOCOLKeyword_2; }
		
		//type=DataType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//DataType
		public RuleCall getTypeDataTypeParserRuleCall_3_0() { return cTypeDataTypeParserRuleCall_3_0; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//'WITH'
		public Keyword getWITHKeyword_5() { return cWITHKeyword_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }
		
		//(params+=TypedParam (',' params+=TypedParam)*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_7_0() { return cParamsAssignment_7_0; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_7_0_0() { return cParamsTypedParamParserRuleCall_7_0_0; }
		
		//(',' params+=TypedParam)*
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//','
		public Keyword getCommaKeyword_7_1_0() { return cCommaKeyword_7_1_0; }
		
		//params+=TypedParam
		public Assignment getParamsAssignment_7_1_1() { return cParamsAssignment_7_1_1; }
		
		//TypedParam
		public RuleCall getParamsTypedParamParserRuleCall_7_1_1_0() { return cParamsTypedParamParserRuleCall_7_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//statements+=Statement*
		public Assignment getStatementsAssignment_10() { return cStatementsAssignment_10; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_10_0() { return cStatementsStatementParserRuleCall_10_0; }
		
		//'RETURN'
		public Keyword getRETURNKeyword_11() { return cRETURNKeyword_11; }
		
		//return=Expression
		public Assignment getReturnAssignment_12() { return cReturnAssignment_12; }
		
		//Expression
		public RuleCall getReturnExpressionParserRuleCall_12_0() { return cReturnExpressionParserRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class TypedParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.TypedParam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeDataTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//TypedParam:
		//    type=DataType name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//type=DataType name=ID
		public Group getGroup() { return cGroup; }
		
		//type=DataType
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//DataType
		public RuleCall getTypeDataTypeParserRuleCall_0_0() { return cTypeDataTypeParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInitializationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAssignmentParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPrintParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cWhileParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cIfParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cIppParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cImmParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Statement:
		//    Initialization | Assignment | Print | While | If | Ipp | Imm;
		@Override public ParserRule getRule() { return rule; }
		
		//Initialization | Assignment | Print | While | If | Ipp | Imm
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Initialization
		public RuleCall getInitializationParserRuleCall_0() { return cInitializationParserRuleCall_0; }
		
		//Assignment
		public RuleCall getAssignmentParserRuleCall_1() { return cAssignmentParserRuleCall_1; }
		
		//Print
		public RuleCall getPrintParserRuleCall_2() { return cPrintParserRuleCall_2; }
		
		//While
		public RuleCall getWhileParserRuleCall_3() { return cWhileParserRuleCall_3; }
		
		//If
		public RuleCall getIfParserRuleCall_4() { return cIfParserRuleCall_4; }
		
		//Ipp
		public RuleCall getIppParserRuleCall_5() { return cIppParserRuleCall_5; }
		
		//Imm
		public RuleCall getImmParserRuleCall_6() { return cImmParserRuleCall_6; }
	}
	public class InitializationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Initialization");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSETKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeDataTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarIDTerminalRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		private final Keyword cASKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueExpressionParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//Initialization:
		//    'SET' type=DataType var=ID 'AS' value=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//'SET' type=DataType var=ID 'AS' value=Expression
		public Group getGroup() { return cGroup; }
		
		//'SET'
		public Keyword getSETKeyword_0() { return cSETKeyword_0; }
		
		//type=DataType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//DataType
		public RuleCall getTypeDataTypeParserRuleCall_1_0() { return cTypeDataTypeParserRuleCall_1_0; }
		
		//var=ID
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_2_0() { return cVarIDTerminalRuleCall_2_0; }
		
		//'AS'
		public Keyword getASKeyword_3() { return cASKeyword_3; }
		
		//value=Expression
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_4_0() { return cValueExpressionParserRuleCall_4_0; }
	}
	public class AssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Assignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNOWKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSETKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cVarAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVarIDTerminalRuleCall_2_0 = (RuleCall)cVarAssignment_2.eContents().get(0);
		private final Keyword cASKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueExpressionParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//Assignment:
		//    'NOW' 'SET' var=ID 'AS' value=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//'NOW' 'SET' var=ID 'AS' value=Expression
		public Group getGroup() { return cGroup; }
		
		//'NOW'
		public Keyword getNOWKeyword_0() { return cNOWKeyword_0; }
		
		//'SET'
		public Keyword getSETKeyword_1() { return cSETKeyword_1; }
		
		//var=ID
		public Assignment getVarAssignment_2() { return cVarAssignment_2; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_2_0() { return cVarIDTerminalRuleCall_2_0; }
		
		//'AS'
		public Keyword getASKeyword_3() { return cASKeyword_3; }
		
		//value=Expression
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//Expression
		public RuleCall getValueExpressionParserRuleCall_4_0() { return cValueExpressionParserRuleCall_4_0; }
	}
	public class PrintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Print");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSHOWKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPrintableAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPrintableExpressionParserRuleCall_2_0 = (RuleCall)cPrintableAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Print:
		//    'SHOW' '(' printable=Expression ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'SHOW' '(' printable=Expression ')'
		public Group getGroup() { return cGroup; }
		
		//'SHOW'
		public Keyword getSHOWKeyword_0() { return cSHOWKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//printable=Expression
		public Assignment getPrintableAssignment_2() { return cPrintableAssignment_2; }
		
		//Expression
		public RuleCall getPrintableExpressionParserRuleCall_2_0() { return cPrintableExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class WhileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.While");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLOOPKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWHILEKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cConditionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConditionBooleanExpressionParserRuleCall_4_0 = (RuleCall)cConditionAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStatementsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStatementsStatementParserRuleCall_7_0 = (RuleCall)cStatementsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//While:
		//    'JARVIS,' 'LOOP' 'WHILE' '(' condition=BooleanExpression ')' '{' statements+=Statement+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,' 'LOOP' 'WHILE' '(' condition=BooleanExpression ')' '{' statements+=Statement+ '}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'LOOP'
		public Keyword getLOOPKeyword_1() { return cLOOPKeyword_1; }
		
		//'WHILE'
		public Keyword getWHILEKeyword_2() { return cWHILEKeyword_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//condition=BooleanExpression
		public Assignment getConditionAssignment_4() { return cConditionAssignment_4; }
		
		//BooleanExpression
		public RuleCall getConditionBooleanExpressionParserRuleCall_4_0() { return cConditionBooleanExpressionParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//statements+=Statement+
		public Assignment getStatementsAssignment_7() { return cStatementsAssignment_7; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_7_0() { return cStatementsStatementParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class IfElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.If");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTRYKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConditionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionBooleanExpressionParserRuleCall_3_0 = (RuleCall)cConditionAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStatementsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStatementsStatementParserRuleCall_6_0 = (RuleCall)cStatementsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//If:
		//    'JARVIS,' 'TRY' '(' condition=BooleanExpression ')' '{' statements+=Statement+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,' 'TRY' '(' condition=BooleanExpression ')' '{' statements+=Statement+ '}'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'TRY'
		public Keyword getTRYKeyword_1() { return cTRYKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//condition=BooleanExpression
		public Assignment getConditionAssignment_3() { return cConditionAssignment_3; }
		
		//BooleanExpression
		public RuleCall getConditionBooleanExpressionParserRuleCall_3_0() { return cConditionBooleanExpressionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//statements+=Statement+
		public Assignment getStatementsAssignment_6() { return cStatementsAssignment_6; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_6_0() { return cStatementsStatementParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class IppElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Ipp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBUMPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//Ipp:
		//    'BUMP' var=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'BUMP' var=ID
		public Group getGroup() { return cGroup; }
		
		//'BUMP'
		public Keyword getBUMPKeyword_0() { return cBUMPKeyword_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class ImmElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Imm");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDROPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//Imm:
		//    'DROP' var=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'DROP' var=ID
		public Group getGroup() { return cGroup; }
		
		//'DROP'
		public Keyword getDROPKeyword_0() { return cDROPKeyword_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class IntValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntValue");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//// Value types
		//IntValue:
		//    val=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//val=INT
		public Assignment getValAssignment() { return cValAssignment; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_0() { return cValINTTerminalRuleCall_0; }
	}
	public class StringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.StringValue");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValSTRINGTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//StringValue:
		//    val=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//val=STRING
		public Assignment getValAssignment() { return cValAssignment; }
		
		//STRING
		public RuleCall getValSTRINGTerminalRuleCall_0() { return cValSTRINGTerminalRuleCall_0; }
	}
	public class BooleanValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cValTRUEKeyword_0_0 = (Keyword)cValAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cBooleanValueAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cFALSEKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//BooleanValue:
		//    val ?= 'TRUE' | {BooleanValue} 'FALSE';
		@Override public ParserRule getRule() { return rule; }
		
		//val ?= 'TRUE' | {BooleanValue} 'FALSE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//val ?= 'TRUE'
		public Assignment getValAssignment_0() { return cValAssignment_0; }
		
		//'TRUE'
		public Keyword getValTRUEKeyword_0_0() { return cValTRUEKeyword_0_0; }
		
		//{BooleanValue} 'FALSE'
		public Group getGroup_1() { return cGroup_1; }
		
		//{BooleanValue}
		public Action getBooleanValueAction_1_0() { return cBooleanValueAction_1_0; }
		
		//'FALSE'
		public Keyword getFALSEKeyword_1_1() { return cFALSEKeyword_1_1; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.Expression");
		private final RuleCall cBooleanExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//// Expressions hierarchy
		//Expression returns Expression:
		//    BooleanExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//BooleanExpression
		public RuleCall getBooleanExpressionParserRuleCall() { return cBooleanExpressionParserRuleCall; }
	}
	public class BooleanExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanExpression");
		private final RuleCall cBooleanOrExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//BooleanExpression returns Expression:
		//    BooleanOrExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//BooleanOrExpression
		public RuleCall getBooleanOrExpressionParserRuleCall() { return cBooleanOrExpressionParserRuleCall; }
	}
	public class BooleanOrExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanOrExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBooleanAndExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBooleanOrExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightBooleanAndExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//BooleanOrExpression returns Expression:
		//    BooleanAndExpression ({BooleanOrExpression.left=current} 'OR' right=BooleanAndExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//BooleanAndExpression ({BooleanOrExpression.left=current} 'OR' right=BooleanAndExpression)*
		public Group getGroup() { return cGroup; }
		
		//BooleanAndExpression
		public RuleCall getBooleanAndExpressionParserRuleCall_0() { return cBooleanAndExpressionParserRuleCall_0; }
		
		//({BooleanOrExpression.left=current} 'OR' right=BooleanAndExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{BooleanOrExpression.left=current}
		public Action getBooleanOrExpressionLeftAction_1_0() { return cBooleanOrExpressionLeftAction_1_0; }
		
		//'OR'
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }
		
		//right=BooleanAndExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//BooleanAndExpression
		public RuleCall getRightBooleanAndExpressionParserRuleCall_1_2_0() { return cRightBooleanAndExpressionParserRuleCall_1_2_0; }
	}
	public class BooleanAndExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanAndExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBooleanEqualityExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBooleanAndExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightBooleanEqualityExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//BooleanAndExpression returns Expression:
		//    BooleanEqualityExpression ({BooleanAndExpression.left=current} 'AND' right=BooleanEqualityExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//BooleanEqualityExpression ({BooleanAndExpression.left=current} 'AND' right=BooleanEqualityExpression)*
		public Group getGroup() { return cGroup; }
		
		//BooleanEqualityExpression
		public RuleCall getBooleanEqualityExpressionParserRuleCall_0() { return cBooleanEqualityExpressionParserRuleCall_0; }
		
		//({BooleanAndExpression.left=current} 'AND' right=BooleanEqualityExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{BooleanAndExpression.left=current}
		public Action getBooleanAndExpressionLeftAction_1_0() { return cBooleanAndExpressionLeftAction_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }
		
		//right=BooleanEqualityExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//BooleanEqualityExpression
		public RuleCall getRightBooleanEqualityExpressionParserRuleCall_1_2_0() { return cRightBooleanEqualityExpressionParserRuleCall_1_2_0; }
	}
	public class BooleanEqualityExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanEqualityExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cBooleanComparisonExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBooleanEqualityExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpEqualsSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpExclamationMarkEqualsSignKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightBooleanComparisonExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//BooleanEqualityExpression returns Expression:
		//    BooleanComparisonExpression ({BooleanEqualityExpression.left=current} op=('=' | '!=') right=BooleanComparisonExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//BooleanComparisonExpression ({BooleanEqualityExpression.left=current} op=('=' | '!=') right=BooleanComparisonExpression)*
		public Group getGroup() { return cGroup; }
		
		//BooleanComparisonExpression
		public RuleCall getBooleanComparisonExpressionParserRuleCall_0() { return cBooleanComparisonExpressionParserRuleCall_0; }
		
		//({BooleanEqualityExpression.left=current} op=('=' | '!=') right=BooleanComparisonExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{BooleanEqualityExpression.left=current}
		public Action getBooleanEqualityExpressionLeftAction_1_0() { return cBooleanEqualityExpressionLeftAction_1_0; }
		
		//op=('=' | '!=')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('=' | '!=')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'='
		public Keyword getOpEqualsSignKeyword_1_1_0_0() { return cOpEqualsSignKeyword_1_1_0_0; }
		
		//'!='
		public Keyword getOpExclamationMarkEqualsSignKeyword_1_1_0_1() { return cOpExclamationMarkEqualsSignKeyword_1_1_0_1; }
		
		//right=BooleanComparisonExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//BooleanComparisonExpression
		public RuleCall getRightBooleanComparisonExpressionParserRuleCall_1_2_0() { return cRightBooleanComparisonExpressionParserRuleCall_1_2_0; }
	}
	public class BooleanComparisonExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.BooleanComparisonExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntComparisonExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNonComparativeBooleanExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//BooleanComparisonExpression returns Expression:
		//    IntComparisonExpression
		//    | NonComparativeBooleanExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//IntComparisonExpression
		//| NonComparativeBooleanExpression
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntComparisonExpression
		public RuleCall getIntComparisonExpressionParserRuleCall_0() { return cIntComparisonExpressionParserRuleCall_0; }
		
		//NonComparativeBooleanExpression
		public RuleCall getNonComparativeBooleanExpressionParserRuleCall_1() { return cNonComparativeBooleanExpressionParserRuleCall_1; }
	}
	public class IntComparisonExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntComparisonExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftIntExpressionParserRuleCall_0_0 = (RuleCall)cLeftAssignment_0.eContents().get(0);
		private final Assignment cOpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cOpAlternatives_1_0 = (Alternatives)cOpAssignment_1.eContents().get(0);
		private final Keyword cOpLessThanSignKeyword_1_0_0 = (Keyword)cOpAlternatives_1_0.eContents().get(0);
		private final Keyword cOpGreaterThanSignKeyword_1_0_1 = (Keyword)cOpAlternatives_1_0.eContents().get(1);
		private final Keyword cOpLessThanSignEqualsSignKeyword_1_0_2 = (Keyword)cOpAlternatives_1_0.eContents().get(2);
		private final Keyword cOpGreaterThanSignEqualsSignKeyword_1_0_3 = (Keyword)cOpAlternatives_1_0.eContents().get(3);
		private final Assignment cRightAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRightIntExpressionParserRuleCall_2_0 = (RuleCall)cRightAssignment_2.eContents().get(0);
		
		//IntComparisonExpression returns Expression:
		//    left=IntExpression op=('<' | '>' | '<=' | '>=') right=IntExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//left=IntExpression op=('<' | '>' | '<=' | '>=') right=IntExpression
		public Group getGroup() { return cGroup; }
		
		//left=IntExpression
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//IntExpression
		public RuleCall getLeftIntExpressionParserRuleCall_0_0() { return cLeftIntExpressionParserRuleCall_0_0; }
		
		//op=('<' | '>' | '<=' | '>=')
		public Assignment getOpAssignment_1() { return cOpAssignment_1; }
		
		//('<' | '>' | '<=' | '>=')
		public Alternatives getOpAlternatives_1_0() { return cOpAlternatives_1_0; }
		
		//'<'
		public Keyword getOpLessThanSignKeyword_1_0_0() { return cOpLessThanSignKeyword_1_0_0; }
		
		//'>'
		public Keyword getOpGreaterThanSignKeyword_1_0_1() { return cOpGreaterThanSignKeyword_1_0_1; }
		
		//'<='
		public Keyword getOpLessThanSignEqualsSignKeyword_1_0_2() { return cOpLessThanSignEqualsSignKeyword_1_0_2; }
		
		//'>='
		public Keyword getOpGreaterThanSignEqualsSignKeyword_1_0_3() { return cOpGreaterThanSignEqualsSignKeyword_1_0_3; }
		
		//right=IntExpression
		public Assignment getRightAssignment_2() { return cRightAssignment_2; }
		
		//IntExpression
		public RuleCall getRightIntExpressionParserRuleCall_2_0() { return cRightIntExpressionParserRuleCall_2_0; }
	}
	public class NonComparativeBooleanExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.NonComparativeBooleanExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionCallParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVariableRefParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cBooleanExpressionParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final RuleCall cBooleanValueParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//NonComparativeBooleanExpression returns Expression:
		//    StringExpression
		//    | FunctionCall
		//    | VariableRef
		//    | '(' BooleanExpression ')'
		//    | BooleanValue;
		@Override public ParserRule getRule() { return rule; }
		
		//StringExpression
		//| FunctionCall
		//| VariableRef
		//| '(' BooleanExpression ')'
		//| BooleanValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringExpression
		public RuleCall getStringExpressionParserRuleCall_0() { return cStringExpressionParserRuleCall_0; }
		
		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_1() { return cFunctionCallParserRuleCall_1; }
		
		//VariableRef
		public RuleCall getVariableRefParserRuleCall_2() { return cVariableRefParserRuleCall_2; }
		
		//'(' BooleanExpression ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//BooleanExpression
		public RuleCall getBooleanExpressionParserRuleCall_3_1() { return cBooleanExpressionParserRuleCall_3_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
		
		//BooleanValue
		public RuleCall getBooleanValueParserRuleCall_4() { return cBooleanValueParserRuleCall_4; }
	}
	public class IntExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntExpression");
		private final RuleCall cIntAdditiveExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//IntExpression returns Expression:
		//    IntAdditiveExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//IntAdditiveExpression
		public RuleCall getIntAdditiveExpressionParserRuleCall() { return cIntAdditiveExpressionParserRuleCall; }
	}
	public class IntAdditiveExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntAdditiveExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIntMultiplicativeExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cIntAdditiveExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpPlusSignKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpHyphenMinusKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightIntMultiplicativeExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//IntAdditiveExpression returns Expression:
		//    IntMultiplicativeExpression ({IntAdditiveExpression.left=current} op=('+' | '-') right=IntMultiplicativeExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//IntMultiplicativeExpression ({IntAdditiveExpression.left=current} op=('+' | '-') right=IntMultiplicativeExpression)*
		public Group getGroup() { return cGroup; }
		
		//IntMultiplicativeExpression
		public RuleCall getIntMultiplicativeExpressionParserRuleCall_0() { return cIntMultiplicativeExpressionParserRuleCall_0; }
		
		//({IntAdditiveExpression.left=current} op=('+' | '-') right=IntMultiplicativeExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{IntAdditiveExpression.left=current}
		public Action getIntAdditiveExpressionLeftAction_1_0() { return cIntAdditiveExpressionLeftAction_1_0; }
		
		//op=('+' | '-')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('+' | '-')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'+'
		public Keyword getOpPlusSignKeyword_1_1_0_0() { return cOpPlusSignKeyword_1_1_0_0; }
		
		//'-'
		public Keyword getOpHyphenMinusKeyword_1_1_0_1() { return cOpHyphenMinusKeyword_1_1_0_1; }
		
		//right=IntMultiplicativeExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//IntMultiplicativeExpression
		public RuleCall getRightIntMultiplicativeExpressionParserRuleCall_1_2_0() { return cRightIntMultiplicativeExpressionParserRuleCall_1_2_0; }
	}
	public class IntMultiplicativeExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntMultiplicativeExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIntPowerExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cIntMultiplicativeExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOpAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOpAlternatives_1_1_0 = (Alternatives)cOpAssignment_1_1.eContents().get(0);
		private final Keyword cOpAsteriskKeyword_1_1_0_0 = (Keyword)cOpAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOpSolidusKeyword_1_1_0_1 = (Keyword)cOpAlternatives_1_1_0.eContents().get(1);
		private final Keyword cOpPercentSignKeyword_1_1_0_2 = (Keyword)cOpAlternatives_1_1_0.eContents().get(2);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightIntPowerExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//IntMultiplicativeExpression returns Expression:
		//    IntPowerExpression ({IntMultiplicativeExpression.left=current} op=('*' | '/' | '%') right=IntPowerExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//IntPowerExpression ({IntMultiplicativeExpression.left=current} op=('*' | '/' | '%') right=IntPowerExpression)*
		public Group getGroup() { return cGroup; }
		
		//IntPowerExpression
		public RuleCall getIntPowerExpressionParserRuleCall_0() { return cIntPowerExpressionParserRuleCall_0; }
		
		//({IntMultiplicativeExpression.left=current} op=('*' | '/' | '%') right=IntPowerExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{IntMultiplicativeExpression.left=current}
		public Action getIntMultiplicativeExpressionLeftAction_1_0() { return cIntMultiplicativeExpressionLeftAction_1_0; }
		
		//op=('*' | '/' | '%')
		public Assignment getOpAssignment_1_1() { return cOpAssignment_1_1; }
		
		//('*' | '/' | '%')
		public Alternatives getOpAlternatives_1_1_0() { return cOpAlternatives_1_1_0; }
		
		//'*'
		public Keyword getOpAsteriskKeyword_1_1_0_0() { return cOpAsteriskKeyword_1_1_0_0; }
		
		//'/'
		public Keyword getOpSolidusKeyword_1_1_0_1() { return cOpSolidusKeyword_1_1_0_1; }
		
		//'%'
		public Keyword getOpPercentSignKeyword_1_1_0_2() { return cOpPercentSignKeyword_1_1_0_2; }
		
		//right=IntPowerExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//IntPowerExpression
		public RuleCall getRightIntPowerExpressionParserRuleCall_1_2_0() { return cRightIntPowerExpressionParserRuleCall_1_2_0; }
	}
	public class IntPowerExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntPowerExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIntPrimaryExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cIntPowerExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cCircumflexAccentKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightIntPrimaryExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//IntPowerExpression returns Expression:
		//    IntPrimaryExpression ({IntPowerExpression.left=current} '^' right=IntPrimaryExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//IntPrimaryExpression ({IntPowerExpression.left=current} '^' right=IntPrimaryExpression)*
		public Group getGroup() { return cGroup; }
		
		//IntPrimaryExpression
		public RuleCall getIntPrimaryExpressionParserRuleCall_0() { return cIntPrimaryExpressionParserRuleCall_0; }
		
		//({IntPowerExpression.left=current} '^' right=IntPrimaryExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{IntPowerExpression.left=current}
		public Action getIntPowerExpressionLeftAction_1_0() { return cIntPowerExpressionLeftAction_1_0; }
		
		//'^'
		public Keyword getCircumflexAccentKeyword_1_1() { return cCircumflexAccentKeyword_1_1; }
		
		//right=IntPrimaryExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//IntPrimaryExpression
		public RuleCall getRightIntPrimaryExpressionParserRuleCall_1_2_0() { return cRightIntPrimaryExpressionParserRuleCall_1_2_0; }
	}
	public class IntPrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.IntPrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionCallParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVariableRefParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cIntExpressionParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//IntPrimaryExpression returns Expression:
		//    IntValue
		//    | FunctionCall
		//    | VariableRef
		//    | '(' IntExpression ')';
		@Override public ParserRule getRule() { return rule; }
		
		//IntValue
		//| FunctionCall
		//| VariableRef
		//| '(' IntExpression ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntValue
		public RuleCall getIntValueParserRuleCall_0() { return cIntValueParserRuleCall_0; }
		
		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_1() { return cFunctionCallParserRuleCall_1; }
		
		//VariableRef
		public RuleCall getVariableRefParserRuleCall_2() { return cVariableRefParserRuleCall_2; }
		
		//'(' IntExpression ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//IntExpression
		public RuleCall getIntExpressionParserRuleCall_3_1() { return cIntExpressionParserRuleCall_3_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
	}
	public class StringExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.StringExpression");
		private final RuleCall cStringConcatExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//StringExpression returns Expression:
		//    StringConcatExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//StringConcatExpression
		public RuleCall getStringConcatExpressionParserRuleCall() { return cStringConcatExpressionParserRuleCall; }
	}
	public class StringConcatExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.StringConcatExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cStringPrimaryExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cStringConcatExpressionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightStringPrimaryExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//StringConcatExpression returns Expression:
		//    StringPrimaryExpression ({StringConcatExpression.left=current} '+' right=StringPrimaryExpression)*;
		@Override public ParserRule getRule() { return rule; }
		
		//StringPrimaryExpression ({StringConcatExpression.left=current} '+' right=StringPrimaryExpression)*
		public Group getGroup() { return cGroup; }
		
		//StringPrimaryExpression
		public RuleCall getStringPrimaryExpressionParserRuleCall_0() { return cStringPrimaryExpressionParserRuleCall_0; }
		
		//({StringConcatExpression.left=current} '+' right=StringPrimaryExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{StringConcatExpression.left=current}
		public Action getStringConcatExpressionLeftAction_1_0() { return cStringConcatExpressionLeftAction_1_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1_1() { return cPlusSignKeyword_1_1; }
		
		//right=StringPrimaryExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//StringPrimaryExpression
		public RuleCall getRightStringPrimaryExpressionParserRuleCall_1_2_0() { return cRightStringPrimaryExpressionParserRuleCall_1_2_0; }
	}
	public class StringPrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.StringPrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFunctionCallParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cVariableRefParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cStringExpressionParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//StringPrimaryExpression returns Expression:
		//    StringValue
		//    | FunctionCall
		//    | VariableRef
		//    | '(' StringExpression ')';
		@Override public ParserRule getRule() { return rule; }
		
		//StringValue
		//| FunctionCall
		//| VariableRef
		//| '(' StringExpression ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringValue
		public RuleCall getStringValueParserRuleCall_0() { return cStringValueParserRuleCall_0; }
		
		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_1() { return cFunctionCallParserRuleCall_1; }
		
		//VariableRef
		public RuleCall getVariableRefParserRuleCall_2() { return cVariableRefParserRuleCall_2; }
		
		//'(' StringExpression ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//StringExpression
		public RuleCall getStringExpressionParserRuleCall_3_1() { return cStringExpressionParserRuleCall_3_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
	}
	public class VariableRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.VariableRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cVarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVarIDTerminalRuleCall_1_0 = (RuleCall)cVarAssignment_1.eContents().get(0);
		
		//VariableRef returns Expression:
		//    {VariableRef} var=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{VariableRef} var=ID
		public Group getGroup() { return cGroup; }
		
		//{VariableRef}
		public Action getVariableRefAction_0() { return cVariableRefAction_0; }
		
		//var=ID
		public Assignment getVarAssignment_1() { return cVarAssignment_1; }
		
		//ID
		public RuleCall getVarIDTerminalRuleCall_1_0() { return cVarIDTerminalRuleCall_1_0; }
	}
	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "edu.upb.lp.JarvisProject.FunctionCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJARVISKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cRUNKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFunctionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cFunctionFunctionCrossReference_2_0 = (CrossReference)cFunctionAssignment_2.eContents().get(0);
		private final RuleCall cFunctionFunctionIDTerminalRuleCall_2_0_1 = (RuleCall)cFunctionFunctionCrossReference_2_0.eContents().get(1);
		private final Keyword cWITHKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Assignment cArgsAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final RuleCall cArgsExpressionParserRuleCall_5_0_0 = (RuleCall)cArgsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cCommaKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cArgsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cArgsExpressionParserRuleCall_5_1_1_0 = (RuleCall)cArgsAssignment_5_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//FunctionCall returns Expression:
		//    'JARVIS,' 'RUN' function=[Function]
		//    'WITH' '(' (args+=Expression (',' args+=Expression)*)? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'JARVIS,' 'RUN' function=[Function]
		//'WITH' '(' (args+=Expression (',' args+=Expression)*)? ')'
		public Group getGroup() { return cGroup; }
		
		//'JARVIS,'
		public Keyword getJARVISKeyword_0() { return cJARVISKeyword_0; }
		
		//'RUN'
		public Keyword getRUNKeyword_1() { return cRUNKeyword_1; }
		
		//function=[Function]
		public Assignment getFunctionAssignment_2() { return cFunctionAssignment_2; }
		
		//[Function]
		public CrossReference getFunctionFunctionCrossReference_2_0() { return cFunctionFunctionCrossReference_2_0; }
		
		//ID
		public RuleCall getFunctionFunctionIDTerminalRuleCall_2_0_1() { return cFunctionFunctionIDTerminalRuleCall_2_0_1; }
		
		//'WITH'
		public Keyword getWITHKeyword_3() { return cWITHKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//(args+=Expression (',' args+=Expression)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//args+=Expression
		public Assignment getArgsAssignment_5_0() { return cArgsAssignment_5_0; }
		
		//Expression
		public RuleCall getArgsExpressionParserRuleCall_5_0_0() { return cArgsExpressionParserRuleCall_5_0_0; }
		
		//(',' args+=Expression)*
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//','
		public Keyword getCommaKeyword_5_1_0() { return cCommaKeyword_5_1_0; }
		
		//args+=Expression
		public Assignment getArgsAssignment_5_1_1() { return cArgsAssignment_5_1_1; }
		
		//Expression
		public RuleCall getArgsExpressionParserRuleCall_5_1_1_0() { return cArgsExpressionParserRuleCall_5_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	
	
	private final ProgramElements pProgram;
	private final DataTypeElements pDataType;
	private final FunctionElements pFunction;
	private final TypedParamElements pTypedParam;
	private final StatementElements pStatement;
	private final InitializationElements pInitialization;
	private final AssignmentElements pAssignment;
	private final PrintElements pPrint;
	private final WhileElements pWhile;
	private final IfElements pIf;
	private final IppElements pIpp;
	private final ImmElements pImm;
	private final IntValueElements pIntValue;
	private final StringValueElements pStringValue;
	private final BooleanValueElements pBooleanValue;
	private final ExpressionElements pExpression;
	private final BooleanExpressionElements pBooleanExpression;
	private final BooleanOrExpressionElements pBooleanOrExpression;
	private final BooleanAndExpressionElements pBooleanAndExpression;
	private final BooleanEqualityExpressionElements pBooleanEqualityExpression;
	private final BooleanComparisonExpressionElements pBooleanComparisonExpression;
	private final IntComparisonExpressionElements pIntComparisonExpression;
	private final NonComparativeBooleanExpressionElements pNonComparativeBooleanExpression;
	private final IntExpressionElements pIntExpression;
	private final IntAdditiveExpressionElements pIntAdditiveExpression;
	private final IntMultiplicativeExpressionElements pIntMultiplicativeExpression;
	private final IntPowerExpressionElements pIntPowerExpression;
	private final IntPrimaryExpressionElements pIntPrimaryExpression;
	private final StringExpressionElements pStringExpression;
	private final StringConcatExpressionElements pStringConcatExpression;
	private final StringPrimaryExpressionElements pStringPrimaryExpression;
	private final VariableRefElements pVariableRef;
	private final FunctionCallElements pFunctionCall;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public JarvisProjectGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pDataType = new DataTypeElements();
		this.pFunction = new FunctionElements();
		this.pTypedParam = new TypedParamElements();
		this.pStatement = new StatementElements();
		this.pInitialization = new InitializationElements();
		this.pAssignment = new AssignmentElements();
		this.pPrint = new PrintElements();
		this.pWhile = new WhileElements();
		this.pIf = new IfElements();
		this.pIpp = new IppElements();
		this.pImm = new ImmElements();
		this.pIntValue = new IntValueElements();
		this.pStringValue = new StringValueElements();
		this.pBooleanValue = new BooleanValueElements();
		this.pExpression = new ExpressionElements();
		this.pBooleanExpression = new BooleanExpressionElements();
		this.pBooleanOrExpression = new BooleanOrExpressionElements();
		this.pBooleanAndExpression = new BooleanAndExpressionElements();
		this.pBooleanEqualityExpression = new BooleanEqualityExpressionElements();
		this.pBooleanComparisonExpression = new BooleanComparisonExpressionElements();
		this.pIntComparisonExpression = new IntComparisonExpressionElements();
		this.pNonComparativeBooleanExpression = new NonComparativeBooleanExpressionElements();
		this.pIntExpression = new IntExpressionElements();
		this.pIntAdditiveExpression = new IntAdditiveExpressionElements();
		this.pIntMultiplicativeExpression = new IntMultiplicativeExpressionElements();
		this.pIntPowerExpression = new IntPowerExpressionElements();
		this.pIntPrimaryExpression = new IntPrimaryExpressionElements();
		this.pStringExpression = new StringExpressionElements();
		this.pStringConcatExpression = new StringConcatExpressionElements();
		this.pStringPrimaryExpression = new StringPrimaryExpressionElements();
		this.pVariableRef = new VariableRefElements();
		this.pFunctionCall = new FunctionCallElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("edu.upb.lp.JarvisProject".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//    name=ID
	//    functions+=Function*
	//    '>' eval+=Expression*;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//DataType:
	//    'INT' | 'STRING' | 'BOOLEAN';
	public DataTypeElements getDataTypeAccess() {
		return pDataType;
	}
	
	public ParserRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//Function:
	//    'JARVIS,' 'CREATE' 'PROTOCOL' type=DataType name=ID
	//    'WITH' '(' (params+=TypedParam (',' params+=TypedParam)*)? ')' '{'
	//        statements+=Statement*
	//        'RETURN' return=Expression
	//    '}';
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//TypedParam:
	//    type=DataType name=ID;
	public TypedParamElements getTypedParamAccess() {
		return pTypedParam;
	}
	
	public ParserRule getTypedParamRule() {
		return getTypedParamAccess().getRule();
	}
	
	//Statement:
	//    Initialization | Assignment | Print | While | If | Ipp | Imm;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Initialization:
	//    'SET' type=DataType var=ID 'AS' value=Expression;
	public InitializationElements getInitializationAccess() {
		return pInitialization;
	}
	
	public ParserRule getInitializationRule() {
		return getInitializationAccess().getRule();
	}
	
	//Assignment:
	//    'NOW' 'SET' var=ID 'AS' value=Expression;
	public AssignmentElements getAssignmentAccess() {
		return pAssignment;
	}
	
	public ParserRule getAssignmentRule() {
		return getAssignmentAccess().getRule();
	}
	
	//Print:
	//    'SHOW' '(' printable=Expression ')';
	public PrintElements getPrintAccess() {
		return pPrint;
	}
	
	public ParserRule getPrintRule() {
		return getPrintAccess().getRule();
	}
	
	//While:
	//    'JARVIS,' 'LOOP' 'WHILE' '(' condition=BooleanExpression ')' '{' statements+=Statement+ '}';
	public WhileElements getWhileAccess() {
		return pWhile;
	}
	
	public ParserRule getWhileRule() {
		return getWhileAccess().getRule();
	}
	
	//If:
	//    'JARVIS,' 'TRY' '(' condition=BooleanExpression ')' '{' statements+=Statement+ '}';
	public IfElements getIfAccess() {
		return pIf;
	}
	
	public ParserRule getIfRule() {
		return getIfAccess().getRule();
	}
	
	//Ipp:
	//    'BUMP' var=ID;
	public IppElements getIppAccess() {
		return pIpp;
	}
	
	public ParserRule getIppRule() {
		return getIppAccess().getRule();
	}
	
	//Imm:
	//    'DROP' var=ID;
	public ImmElements getImmAccess() {
		return pImm;
	}
	
	public ParserRule getImmRule() {
		return getImmAccess().getRule();
	}
	
	//// Value types
	//IntValue:
	//    val=INT;
	public IntValueElements getIntValueAccess() {
		return pIntValue;
	}
	
	public ParserRule getIntValueRule() {
		return getIntValueAccess().getRule();
	}
	
	//StringValue:
	//    val=STRING;
	public StringValueElements getStringValueAccess() {
		return pStringValue;
	}
	
	public ParserRule getStringValueRule() {
		return getStringValueAccess().getRule();
	}
	
	//BooleanValue:
	//    val ?= 'TRUE' | {BooleanValue} 'FALSE';
	public BooleanValueElements getBooleanValueAccess() {
		return pBooleanValue;
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//// Expressions hierarchy
	//Expression returns Expression:
	//    BooleanExpression;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//BooleanExpression returns Expression:
	//    BooleanOrExpression;
	public BooleanExpressionElements getBooleanExpressionAccess() {
		return pBooleanExpression;
	}
	
	public ParserRule getBooleanExpressionRule() {
		return getBooleanExpressionAccess().getRule();
	}
	
	//BooleanOrExpression returns Expression:
	//    BooleanAndExpression ({BooleanOrExpression.left=current} 'OR' right=BooleanAndExpression)*;
	public BooleanOrExpressionElements getBooleanOrExpressionAccess() {
		return pBooleanOrExpression;
	}
	
	public ParserRule getBooleanOrExpressionRule() {
		return getBooleanOrExpressionAccess().getRule();
	}
	
	//BooleanAndExpression returns Expression:
	//    BooleanEqualityExpression ({BooleanAndExpression.left=current} 'AND' right=BooleanEqualityExpression)*;
	public BooleanAndExpressionElements getBooleanAndExpressionAccess() {
		return pBooleanAndExpression;
	}
	
	public ParserRule getBooleanAndExpressionRule() {
		return getBooleanAndExpressionAccess().getRule();
	}
	
	//BooleanEqualityExpression returns Expression:
	//    BooleanComparisonExpression ({BooleanEqualityExpression.left=current} op=('=' | '!=') right=BooleanComparisonExpression)*;
	public BooleanEqualityExpressionElements getBooleanEqualityExpressionAccess() {
		return pBooleanEqualityExpression;
	}
	
	public ParserRule getBooleanEqualityExpressionRule() {
		return getBooleanEqualityExpressionAccess().getRule();
	}
	
	//BooleanComparisonExpression returns Expression:
	//    IntComparisonExpression
	//    | NonComparativeBooleanExpression;
	public BooleanComparisonExpressionElements getBooleanComparisonExpressionAccess() {
		return pBooleanComparisonExpression;
	}
	
	public ParserRule getBooleanComparisonExpressionRule() {
		return getBooleanComparisonExpressionAccess().getRule();
	}
	
	//IntComparisonExpression returns Expression:
	//    left=IntExpression op=('<' | '>' | '<=' | '>=') right=IntExpression;
	public IntComparisonExpressionElements getIntComparisonExpressionAccess() {
		return pIntComparisonExpression;
	}
	
	public ParserRule getIntComparisonExpressionRule() {
		return getIntComparisonExpressionAccess().getRule();
	}
	
	//NonComparativeBooleanExpression returns Expression:
	//    StringExpression
	//    | FunctionCall
	//    | VariableRef
	//    | '(' BooleanExpression ')'
	//    | BooleanValue;
	public NonComparativeBooleanExpressionElements getNonComparativeBooleanExpressionAccess() {
		return pNonComparativeBooleanExpression;
	}
	
	public ParserRule getNonComparativeBooleanExpressionRule() {
		return getNonComparativeBooleanExpressionAccess().getRule();
	}
	
	//IntExpression returns Expression:
	//    IntAdditiveExpression;
	public IntExpressionElements getIntExpressionAccess() {
		return pIntExpression;
	}
	
	public ParserRule getIntExpressionRule() {
		return getIntExpressionAccess().getRule();
	}
	
	//IntAdditiveExpression returns Expression:
	//    IntMultiplicativeExpression ({IntAdditiveExpression.left=current} op=('+' | '-') right=IntMultiplicativeExpression)*;
	public IntAdditiveExpressionElements getIntAdditiveExpressionAccess() {
		return pIntAdditiveExpression;
	}
	
	public ParserRule getIntAdditiveExpressionRule() {
		return getIntAdditiveExpressionAccess().getRule();
	}
	
	//IntMultiplicativeExpression returns Expression:
	//    IntPowerExpression ({IntMultiplicativeExpression.left=current} op=('*' | '/' | '%') right=IntPowerExpression)*;
	public IntMultiplicativeExpressionElements getIntMultiplicativeExpressionAccess() {
		return pIntMultiplicativeExpression;
	}
	
	public ParserRule getIntMultiplicativeExpressionRule() {
		return getIntMultiplicativeExpressionAccess().getRule();
	}
	
	//IntPowerExpression returns Expression:
	//    IntPrimaryExpression ({IntPowerExpression.left=current} '^' right=IntPrimaryExpression)*;
	public IntPowerExpressionElements getIntPowerExpressionAccess() {
		return pIntPowerExpression;
	}
	
	public ParserRule getIntPowerExpressionRule() {
		return getIntPowerExpressionAccess().getRule();
	}
	
	//IntPrimaryExpression returns Expression:
	//    IntValue
	//    | FunctionCall
	//    | VariableRef
	//    | '(' IntExpression ')';
	public IntPrimaryExpressionElements getIntPrimaryExpressionAccess() {
		return pIntPrimaryExpression;
	}
	
	public ParserRule getIntPrimaryExpressionRule() {
		return getIntPrimaryExpressionAccess().getRule();
	}
	
	//StringExpression returns Expression:
	//    StringConcatExpression;
	public StringExpressionElements getStringExpressionAccess() {
		return pStringExpression;
	}
	
	public ParserRule getStringExpressionRule() {
		return getStringExpressionAccess().getRule();
	}
	
	//StringConcatExpression returns Expression:
	//    StringPrimaryExpression ({StringConcatExpression.left=current} '+' right=StringPrimaryExpression)*;
	public StringConcatExpressionElements getStringConcatExpressionAccess() {
		return pStringConcatExpression;
	}
	
	public ParserRule getStringConcatExpressionRule() {
		return getStringConcatExpressionAccess().getRule();
	}
	
	//StringPrimaryExpression returns Expression:
	//    StringValue
	//    | FunctionCall
	//    | VariableRef
	//    | '(' StringExpression ')';
	public StringPrimaryExpressionElements getStringPrimaryExpressionAccess() {
		return pStringPrimaryExpression;
	}
	
	public ParserRule getStringPrimaryExpressionRule() {
		return getStringPrimaryExpressionAccess().getRule();
	}
	
	//VariableRef returns Expression:
	//    {VariableRef} var=ID;
	public VariableRefElements getVariableRefAccess() {
		return pVariableRef;
	}
	
	public ParserRule getVariableRefRule() {
		return getVariableRefAccess().getRule();
	}
	
	//FunctionCall returns Expression:
	//    'JARVIS,' 'RUN' function=[Function]
	//    'WITH' '(' (args+=Expression (',' args+=Expression)*)? ')';
	public FunctionCallElements getFunctionCallAccess() {
		return pFunctionCall;
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
