/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
