/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Int</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getFunctionInt()
 * @model
 * @generated
 */
public interface FunctionInt extends Function
{
} // FunctionInt
