/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Additive Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getIntAdditiveExpression()
 * @model
 * @generated
 */
public interface IntAdditiveExpression extends Expression
{
} // IntAdditiveExpression
