/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.jarvisProject.Print#getPrintable <em>Printable</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getPrint()
 * @model
 * @generated
 */
public interface Print extends Statement
{
  /**
   * Returns the value of the '<em><b>Printable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Printable</em>' containment reference.
   * @see #setPrintable(Expression)
   * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getPrint_Printable()
   * @model containment="true"
   * @generated
   */
  Expression getPrintable();

  /**
   * Sets the value of the '{@link edu.upb.lp.jarvisProject.Print#getPrintable <em>Printable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Printable</em>' containment reference.
   * @see #getPrintable()
   * @generated
   */
  void setPrintable(Expression value);

} // Print
