/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.jarvisProject.Program#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.jarvisProject.Program#getFunctions <em>Functions</em>}</li>
 *   <li>{@link edu.upb.lp.jarvisProject.Program#getEval <em>Eval</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getProgram_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.jarvisProject.Program#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.jarvisProject.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getProgram_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunctions();

  /**
   * Returns the value of the '<em><b>Eval</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.jarvisProject.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eval</em>' containment reference list.
   * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getProgram_Eval()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getEval();

} // Program
