/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.jarvisProject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Concat Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.upb.lp.jarvisProject.JarvisProjectPackage#getStringConcatExpression()
 * @model
 * @generated
 */
public interface StringConcatExpression extends Expression
{
} // StringConcatExpression
