/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.generator

import edu.upb.lp.jarvisProject.AdditiveExpression
import edu.upb.lp.jarvisProject.AndExpression
import edu.upb.lp.jarvisProject.Assignment
import edu.upb.lp.jarvisProject.BooleanValue
import edu.upb.lp.jarvisProject.ComparisonExpression
import edu.upb.lp.jarvisProject.EqualityExpression
import edu.upb.lp.jarvisProject.FunctionBoolean
import edu.upb.lp.jarvisProject.FunctionCall
import edu.upb.lp.jarvisProject.FunctionInt
import edu.upb.lp.jarvisProject.FunctionString
import edu.upb.lp.jarvisProject.If
import edu.upb.lp.jarvisProject.Imm
import edu.upb.lp.jarvisProject.Initialization
import edu.upb.lp.jarvisProject.IntValue
import edu.upb.lp.jarvisProject.Ipp
import edu.upb.lp.jarvisProject.MultiplicativeExpression
import edu.upb.lp.jarvisProject.OrExpression
import edu.upb.lp.jarvisProject.Print
import edu.upb.lp.jarvisProject.Program
import edu.upb.lp.jarvisProject.StringValue
import edu.upb.lp.jarvisProject.TypedParam
import edu.upb.lp.jarvisProject.VariableRef
import edu.upb.lp.jarvisProject.While
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class JarvisProjectGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
//		fsa.generateFile('greetings.txt', 'People to greet: ' + 
//			resource.allContents
//				.filter(Greeting)
//				.map[name]
//				.join(', '))
		val program = resource.allContents.head as Program
		fsa.generateFile(program.name + ".java", generateProgram(program))
	}
	
	def generateProgram(Program program) '''
		public class «program.name» {
			«FOR function : program.functions»
				«generateFunction(function)»
			«ENDFOR»
	
			public static void main(String[] args) {
				«FOR expr : program.eval»
					System.out.println(«generateExpression(expr)»);
				«ENDFOR»
			}
		}
	'''
	
	def dispatch generateFunction(FunctionInt function) '''
		public static int «function.name»(«function.params.map[generateTypedParam].join(', ')») {
			«FOR stmt : function.statements»
				«generateStatement(stmt)»
			«ENDFOR»
			return «generateExpression(function.^return)»;
		}
	'''
	
	def dispatch generateFunction(FunctionString function) '''
		public static String «function.name»(«function.params.map[generateTypedParam].join(', ')») {
			«FOR stmt : function.statements»
				«generateStatement(stmt)»
			«ENDFOR»
			return «generateExpression(function.^return)»;
		}
	'''
	
	def dispatch generateFunction(FunctionBoolean function) '''
		public static boolean «function.name»(«function.params.map[generateTypedParam].join(', ')») {
			«FOR stmt : function.statements»
				«generateStatement(stmt)»
			«ENDFOR»
			return «generateExpression(function.^return)»;
		}
	'''
	
	def generateTypedParam (TypedParam t) '''
		«toJavaType(t.type)» «t.name»
	'''
	
	def dispatch generateStatement(Initialization stmt) '''
		«toJavaType(stmt.type)» «stmt.^var» = «generateExpression(stmt.value)»;
	'''
	
	def dispatch generateStatement(Assignment stmt) '''
		«stmt.^var» = «generateExpression(stmt.value)»;
	'''
	
	def dispatch generateStatement(Print stmt) '''
		System.out.println(«generateExpression(stmt.printable)»);
	'''
	
	def dispatch String generateStatement(While stmt) '''
		while («generateExpression(stmt.condition)») {
			«FOR s : stmt.statements»
				«generateStatement(s)»
			«ENDFOR»
		}
	'''
	
	def dispatch String generateStatement(If stmt) '''
		if («generateExpression(stmt.condition)») {
			«FOR s : stmt.statements»
				«generateStatement(s)»
			«ENDFOR»
		}
	'''
	
	def dispatch generateStatement(Ipp stmt) '''
		«stmt.^var»++;
	'''
	
	def dispatch generateStatement(Imm stmt) '''
		«stmt.^var»--;
	'''
	
	def dispatch generateExpression(IntValue expr) '''«expr.^val»'''
	
	def dispatch generateExpression(StringValue expr) '''"«expr.^val»"'''
	
	def dispatch generateExpression(BooleanValue expr) '''«expr.^val»'''
	
	def dispatch generateExpression(VariableRef expr) '''«expr.^var»'''
	
	def dispatch String generateExpression(FunctionCall expr) '''
		«expr.function.name»(«expr.args.map[generateExpression].join(', ')»)
	'''
	
	def dispatch String generateExpression(OrExpression expr) '''
		(«generateExpression(expr.left)» || «generateExpression(expr.right)»)
	'''
	
	def dispatch String generateExpression(AndExpression expr) '''
		(«generateExpression(expr.left)» && «generateExpression(expr.right)»)
	'''
	
	def dispatch String generateExpression(EqualityExpression expr) '''
		(«generateExpression(expr.left)» «expr.op» «generateExpression(expr.right)»)
	'''
	
	def dispatch String generateExpression(ComparisonExpression expr) '''
		(«generateExpression(expr.left)» «expr.op» «generateExpression(expr.right)»)
	'''
	
	def dispatch String generateExpression(AdditiveExpression expr) '''
		(«generateExpression(expr.left)» «expr.op» «generateExpression(expr.right)»)
	'''
	
	def dispatch String generateExpression(MultiplicativeExpression expr) '''
		(«generateExpression(expr.left)» «expr.op» «generateExpression(expr.right)»)
	'''
	
	def toJavaType(String type) {
		switch type {
			case 'NUMBER': 'int'
			case 'TEXT': 'String'
			case 'BOOLEAN': 'boolean'
			default: 'Object'
		}
	}
}
