/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.serializer;

import com.google.inject.Inject;
import edu.upb.lp.jarvisProject.AdditiveExpression;
import edu.upb.lp.jarvisProject.AndExpression;
import edu.upb.lp.jarvisProject.Assignment;
import edu.upb.lp.jarvisProject.BooleanValue;
import edu.upb.lp.jarvisProject.ComparisonExpression;
import edu.upb.lp.jarvisProject.EqualityExpression;
import edu.upb.lp.jarvisProject.FunctionBoolean;
import edu.upb.lp.jarvisProject.FunctionCall;
import edu.upb.lp.jarvisProject.FunctionInt;
import edu.upb.lp.jarvisProject.FunctionString;
import edu.upb.lp.jarvisProject.If;
import edu.upb.lp.jarvisProject.Imm;
import edu.upb.lp.jarvisProject.Initialization;
import edu.upb.lp.jarvisProject.IntValue;
import edu.upb.lp.jarvisProject.Ipp;
import edu.upb.lp.jarvisProject.JarvisProjectPackage;
import edu.upb.lp.jarvisProject.MultiplicativeExpression;
import edu.upb.lp.jarvisProject.OrExpression;
import edu.upb.lp.jarvisProject.Print;
import edu.upb.lp.jarvisProject.Program;
import edu.upb.lp.jarvisProject.StringValue;
import edu.upb.lp.jarvisProject.TypedParam;
import edu.upb.lp.jarvisProject.VariableRef;
import edu.upb.lp.jarvisProject.While;
import edu.upb.lp.services.JarvisProjectGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class JarvisProjectSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private JarvisProjectGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == JarvisProjectPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case JarvisProjectPackage.ADDITIVE_EXPRESSION:
				sequence_AdditiveExpression(context, (AdditiveExpression) semanticObject); 
				return; 
			case JarvisProjectPackage.AND_EXPRESSION:
				sequence_AndExpression(context, (AndExpression) semanticObject); 
				return; 
			case JarvisProjectPackage.ASSIGNMENT:
				sequence_Assignment(context, (Assignment) semanticObject); 
				return; 
			case JarvisProjectPackage.BOOLEAN_VALUE:
				sequence_BooleanValue(context, (BooleanValue) semanticObject); 
				return; 
			case JarvisProjectPackage.COMPARISON_EXPRESSION:
				sequence_ComparisonExpression(context, (ComparisonExpression) semanticObject); 
				return; 
			case JarvisProjectPackage.EQUALITY_EXPRESSION:
				sequence_EqualityExpression(context, (EqualityExpression) semanticObject); 
				return; 
			case JarvisProjectPackage.FUNCTION_BOOLEAN:
				sequence_FunctionBoolean(context, (FunctionBoolean) semanticObject); 
				return; 
			case JarvisProjectPackage.FUNCTION_CALL:
				sequence_FunctionCall(context, (FunctionCall) semanticObject); 
				return; 
			case JarvisProjectPackage.FUNCTION_INT:
				sequence_FunctionInt(context, (FunctionInt) semanticObject); 
				return; 
			case JarvisProjectPackage.FUNCTION_STRING:
				sequence_FunctionString(context, (FunctionString) semanticObject); 
				return; 
			case JarvisProjectPackage.IF:
				sequence_If(context, (If) semanticObject); 
				return; 
			case JarvisProjectPackage.IMM:
				sequence_Imm(context, (Imm) semanticObject); 
				return; 
			case JarvisProjectPackage.INITIALIZATION:
				sequence_Initialization(context, (Initialization) semanticObject); 
				return; 
			case JarvisProjectPackage.INT_VALUE:
				sequence_IntValue(context, (IntValue) semanticObject); 
				return; 
			case JarvisProjectPackage.IPP:
				sequence_Ipp(context, (Ipp) semanticObject); 
				return; 
			case JarvisProjectPackage.MULTIPLICATIVE_EXPRESSION:
				sequence_MultiplicativeExpression(context, (MultiplicativeExpression) semanticObject); 
				return; 
			case JarvisProjectPackage.OR_EXPRESSION:
				sequence_OrExpression(context, (OrExpression) semanticObject); 
				return; 
			case JarvisProjectPackage.PRINT:
				sequence_Print(context, (Print) semanticObject); 
				return; 
			case JarvisProjectPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case JarvisProjectPackage.STRING_VALUE:
				sequence_StringValue(context, (StringValue) semanticObject); 
				return; 
			case JarvisProjectPackage.TYPED_PARAM:
				sequence_TypedParam(context, (TypedParam) semanticObject); 
				return; 
			case JarvisProjectPackage.VARIABLE_REF:
				sequence_VariableRef(context, (VariableRef) semanticObject); 
				return; 
			case JarvisProjectPackage.WHILE:
				sequence_While(context, (While) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns AdditiveExpression
	 *     OrExpression returns AdditiveExpression
	 *     OrExpression.OrExpression_1_0 returns AdditiveExpression
	 *     AndExpression returns AdditiveExpression
	 *     AndExpression.AndExpression_1_0 returns AdditiveExpression
	 *     EqualityExpression returns AdditiveExpression
	 *     EqualityExpression.EqualityExpression_1_0 returns AdditiveExpression
	 *     ComparisonExpression returns AdditiveExpression
	 *     ComparisonExpression.ComparisonExpression_1_0 returns AdditiveExpression
	 *     AdditiveExpression returns AdditiveExpression
	 *     AdditiveExpression.AdditiveExpression_1_0 returns AdditiveExpression
	 *     MultiplicativeExpression returns AdditiveExpression
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns AdditiveExpression
	 *     PrimaryExpression returns AdditiveExpression
	 *
	 * Constraint:
	 *     (left=AdditiveExpression_AdditiveExpression_1_0 (op='+' | op='-') right=MultiplicativeExpression)
	 * </pre>
	 */
	protected void sequence_AdditiveExpression(ISerializationContext context, AdditiveExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns AndExpression
	 *     OrExpression returns AndExpression
	 *     OrExpression.OrExpression_1_0 returns AndExpression
	 *     AndExpression returns AndExpression
	 *     AndExpression.AndExpression_1_0 returns AndExpression
	 *     EqualityExpression returns AndExpression
	 *     EqualityExpression.EqualityExpression_1_0 returns AndExpression
	 *     ComparisonExpression returns AndExpression
	 *     ComparisonExpression.ComparisonExpression_1_0 returns AndExpression
	 *     AdditiveExpression returns AndExpression
	 *     AdditiveExpression.AdditiveExpression_1_0 returns AndExpression
	 *     MultiplicativeExpression returns AndExpression
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns AndExpression
	 *     PrimaryExpression returns AndExpression
	 *
	 * Constraint:
	 *     (left=AndExpression_AndExpression_1_0 right=EqualityExpression)
	 * </pre>
	 */
	protected void sequence_AndExpression(ISerializationContext context, AndExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.AND_EXPRESSION__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.AND_EXPRESSION__LEFT));
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.AND_EXPRESSION__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.AND_EXPRESSION__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAndExpressionAccess().getAndExpressionLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getAndExpressionAccess().getRightEqualityExpressionParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Assignment
	 *     Assignment returns Assignment
	 *
	 * Constraint:
	 *     (var=ID value=Expression)
	 * </pre>
	 */
	protected void sequence_Assignment(ISerializationContext context, Assignment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.ASSIGNMENT__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.ASSIGNMENT__VAR));
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.ASSIGNMENT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.ASSIGNMENT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAssignmentAccess().getVarIDTerminalRuleCall_3_0(), semanticObject.getVar());
		feeder.accept(grammarAccess.getAssignmentAccess().getValueExpressionParserRuleCall_5_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     BooleanValue returns BooleanValue
	 *     Expression returns BooleanValue
	 *     OrExpression returns BooleanValue
	 *     OrExpression.OrExpression_1_0 returns BooleanValue
	 *     AndExpression returns BooleanValue
	 *     AndExpression.AndExpression_1_0 returns BooleanValue
	 *     EqualityExpression returns BooleanValue
	 *     EqualityExpression.EqualityExpression_1_0 returns BooleanValue
	 *     ComparisonExpression returns BooleanValue
	 *     ComparisonExpression.ComparisonExpression_1_0 returns BooleanValue
	 *     AdditiveExpression returns BooleanValue
	 *     AdditiveExpression.AdditiveExpression_1_0 returns BooleanValue
	 *     MultiplicativeExpression returns BooleanValue
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns BooleanValue
	 *     PrimaryExpression returns BooleanValue
	 *
	 * Constraint:
	 *     val?='TRUE'?
	 * </pre>
	 */
	protected void sequence_BooleanValue(ISerializationContext context, BooleanValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns ComparisonExpression
	 *     OrExpression returns ComparisonExpression
	 *     OrExpression.OrExpression_1_0 returns ComparisonExpression
	 *     AndExpression returns ComparisonExpression
	 *     AndExpression.AndExpression_1_0 returns ComparisonExpression
	 *     EqualityExpression returns ComparisonExpression
	 *     EqualityExpression.EqualityExpression_1_0 returns ComparisonExpression
	 *     ComparisonExpression returns ComparisonExpression
	 *     ComparisonExpression.ComparisonExpression_1_0 returns ComparisonExpression
	 *     AdditiveExpression returns ComparisonExpression
	 *     AdditiveExpression.AdditiveExpression_1_0 returns ComparisonExpression
	 *     MultiplicativeExpression returns ComparisonExpression
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns ComparisonExpression
	 *     PrimaryExpression returns ComparisonExpression
	 *
	 * Constraint:
	 *     (left=ComparisonExpression_ComparisonExpression_1_0 (op='&lt;' | op='&gt;' | op='&lt;=' | op='&gt;=') right=AdditiveExpression)
	 * </pre>
	 */
	protected void sequence_ComparisonExpression(ISerializationContext context, ComparisonExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns EqualityExpression
	 *     OrExpression returns EqualityExpression
	 *     OrExpression.OrExpression_1_0 returns EqualityExpression
	 *     AndExpression returns EqualityExpression
	 *     AndExpression.AndExpression_1_0 returns EqualityExpression
	 *     EqualityExpression returns EqualityExpression
	 *     EqualityExpression.EqualityExpression_1_0 returns EqualityExpression
	 *     ComparisonExpression returns EqualityExpression
	 *     ComparisonExpression.ComparisonExpression_1_0 returns EqualityExpression
	 *     AdditiveExpression returns EqualityExpression
	 *     AdditiveExpression.AdditiveExpression_1_0 returns EqualityExpression
	 *     MultiplicativeExpression returns EqualityExpression
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns EqualityExpression
	 *     PrimaryExpression returns EqualityExpression
	 *
	 * Constraint:
	 *     (left=EqualityExpression_EqualityExpression_1_0 (op='==' | op='!=') right=ComparisonExpression)
	 * </pre>
	 */
	protected void sequence_EqualityExpression(ISerializationContext context, EqualityExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Function returns FunctionBoolean
	 *     FunctionBoolean returns FunctionBoolean
	 *
	 * Constraint:
	 *     (name=ID (params+=TypedParam params+=TypedParam*)? statements+=Statement* return=Expression)
	 * </pre>
	 */
	protected void sequence_FunctionBoolean(ISerializationContext context, FunctionBoolean semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns FunctionCall
	 *     OrExpression returns FunctionCall
	 *     OrExpression.OrExpression_1_0 returns FunctionCall
	 *     AndExpression returns FunctionCall
	 *     AndExpression.AndExpression_1_0 returns FunctionCall
	 *     EqualityExpression returns FunctionCall
	 *     EqualityExpression.EqualityExpression_1_0 returns FunctionCall
	 *     ComparisonExpression returns FunctionCall
	 *     ComparisonExpression.ComparisonExpression_1_0 returns FunctionCall
	 *     AdditiveExpression returns FunctionCall
	 *     AdditiveExpression.AdditiveExpression_1_0 returns FunctionCall
	 *     MultiplicativeExpression returns FunctionCall
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns FunctionCall
	 *     PrimaryExpression returns FunctionCall
	 *     FunctionCall returns FunctionCall
	 *
	 * Constraint:
	 *     (function=[Function|ID] (args+=Expression args+=Expression*)?)
	 * </pre>
	 */
	protected void sequence_FunctionCall(ISerializationContext context, FunctionCall semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Function returns FunctionInt
	 *     FunctionInt returns FunctionInt
	 *
	 * Constraint:
	 *     (name=ID (params+=TypedParam params+=TypedParam*)? statements+=Statement* return=Expression)
	 * </pre>
	 */
	protected void sequence_FunctionInt(ISerializationContext context, FunctionInt semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Function returns FunctionString
	 *     FunctionString returns FunctionString
	 *
	 * Constraint:
	 *     (name=ID (params+=TypedParam params+=TypedParam*)? statements+=Statement* return=Expression)
	 * </pre>
	 */
	protected void sequence_FunctionString(ISerializationContext context, FunctionString semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns If
	 *     If returns If
	 *
	 * Constraint:
	 *     (condition=Expression statements+=Statement+)
	 * </pre>
	 */
	protected void sequence_If(ISerializationContext context, If semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Imm
	 *     Imm returns Imm
	 *
	 * Constraint:
	 *     var=ID
	 * </pre>
	 */
	protected void sequence_Imm(ISerializationContext context, Imm semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.IMM__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.IMM__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImmAccess().getVarIDTerminalRuleCall_2_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Initialization
	 *     Initialization returns Initialization
	 *
	 * Constraint:
	 *     (type=DataType var=ID value=Expression)
	 * </pre>
	 */
	protected void sequence_Initialization(ISerializationContext context, Initialization semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.INITIALIZATION__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.INITIALIZATION__TYPE));
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.INITIALIZATION__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.INITIALIZATION__VAR));
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.INITIALIZATION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.INITIALIZATION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInitializationAccess().getTypeDataTypeParserRuleCall_2_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getInitializationAccess().getVarIDTerminalRuleCall_3_0(), semanticObject.getVar());
		feeder.accept(grammarAccess.getInitializationAccess().getValueExpressionParserRuleCall_5_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     IntValue returns IntValue
	 *     Expression returns IntValue
	 *     OrExpression returns IntValue
	 *     OrExpression.OrExpression_1_0 returns IntValue
	 *     AndExpression returns IntValue
	 *     AndExpression.AndExpression_1_0 returns IntValue
	 *     EqualityExpression returns IntValue
	 *     EqualityExpression.EqualityExpression_1_0 returns IntValue
	 *     ComparisonExpression returns IntValue
	 *     ComparisonExpression.ComparisonExpression_1_0 returns IntValue
	 *     AdditiveExpression returns IntValue
	 *     AdditiveExpression.AdditiveExpression_1_0 returns IntValue
	 *     MultiplicativeExpression returns IntValue
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns IntValue
	 *     PrimaryExpression returns IntValue
	 *
	 * Constraint:
	 *     val=INT
	 * </pre>
	 */
	protected void sequence_IntValue(ISerializationContext context, IntValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.INT_VALUE__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.INT_VALUE__VAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntValueAccess().getValINTTerminalRuleCall_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Ipp
	 *     Ipp returns Ipp
	 *
	 * Constraint:
	 *     var=ID
	 * </pre>
	 */
	protected void sequence_Ipp(ISerializationContext context, Ipp semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.IPP__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.IPP__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIppAccess().getVarIDTerminalRuleCall_2_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns MultiplicativeExpression
	 *     OrExpression returns MultiplicativeExpression
	 *     OrExpression.OrExpression_1_0 returns MultiplicativeExpression
	 *     AndExpression returns MultiplicativeExpression
	 *     AndExpression.AndExpression_1_0 returns MultiplicativeExpression
	 *     EqualityExpression returns MultiplicativeExpression
	 *     EqualityExpression.EqualityExpression_1_0 returns MultiplicativeExpression
	 *     ComparisonExpression returns MultiplicativeExpression
	 *     ComparisonExpression.ComparisonExpression_1_0 returns MultiplicativeExpression
	 *     AdditiveExpression returns MultiplicativeExpression
	 *     AdditiveExpression.AdditiveExpression_1_0 returns MultiplicativeExpression
	 *     MultiplicativeExpression returns MultiplicativeExpression
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns MultiplicativeExpression
	 *     PrimaryExpression returns MultiplicativeExpression
	 *
	 * Constraint:
	 *     (left=MultiplicativeExpression_MultiplicativeExpression_1_0 (op='*' | op='/' | op='%') right=PrimaryExpression)
	 * </pre>
	 */
	protected void sequence_MultiplicativeExpression(ISerializationContext context, MultiplicativeExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns OrExpression
	 *     OrExpression returns OrExpression
	 *     OrExpression.OrExpression_1_0 returns OrExpression
	 *     AndExpression returns OrExpression
	 *     AndExpression.AndExpression_1_0 returns OrExpression
	 *     EqualityExpression returns OrExpression
	 *     EqualityExpression.EqualityExpression_1_0 returns OrExpression
	 *     ComparisonExpression returns OrExpression
	 *     ComparisonExpression.ComparisonExpression_1_0 returns OrExpression
	 *     AdditiveExpression returns OrExpression
	 *     AdditiveExpression.AdditiveExpression_1_0 returns OrExpression
	 *     MultiplicativeExpression returns OrExpression
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns OrExpression
	 *     PrimaryExpression returns OrExpression
	 *
	 * Constraint:
	 *     (left=OrExpression_OrExpression_1_0 right=AndExpression)
	 * </pre>
	 */
	protected void sequence_OrExpression(ISerializationContext context, OrExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.OR_EXPRESSION__LEFT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.OR_EXPRESSION__LEFT));
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.OR_EXPRESSION__RIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.OR_EXPRESSION__RIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getOrExpressionAccess().getOrExpressionLeftAction_1_0(), semanticObject.getLeft());
		feeder.accept(grammarAccess.getOrExpressionAccess().getRightAndExpressionParserRuleCall_1_2_0(), semanticObject.getRight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Print
	 *     Print returns Print
	 *
	 * Constraint:
	 *     printable=Expression
	 * </pre>
	 */
	protected void sequence_Print(ISerializationContext context, Print semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.PRINT__PRINTABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.PRINT__PRINTABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPrintAccess().getPrintableExpressionParserRuleCall_3_0(), semanticObject.getPrintable());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     (name=ID functions+=Function* eval+=Expression*)
	 * </pre>
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StringValue returns StringValue
	 *     Expression returns StringValue
	 *     OrExpression returns StringValue
	 *     OrExpression.OrExpression_1_0 returns StringValue
	 *     AndExpression returns StringValue
	 *     AndExpression.AndExpression_1_0 returns StringValue
	 *     EqualityExpression returns StringValue
	 *     EqualityExpression.EqualityExpression_1_0 returns StringValue
	 *     ComparisonExpression returns StringValue
	 *     ComparisonExpression.ComparisonExpression_1_0 returns StringValue
	 *     AdditiveExpression returns StringValue
	 *     AdditiveExpression.AdditiveExpression_1_0 returns StringValue
	 *     MultiplicativeExpression returns StringValue
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns StringValue
	 *     PrimaryExpression returns StringValue
	 *
	 * Constraint:
	 *     val=STRING
	 * </pre>
	 */
	protected void sequence_StringValue(ISerializationContext context, StringValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.STRING_VALUE__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.STRING_VALUE__VAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringValueAccess().getValSTRINGTerminalRuleCall_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypedParam returns TypedParam
	 *
	 * Constraint:
	 *     (type=DataType name=ID)
	 * </pre>
	 */
	protected void sequence_TypedParam(ISerializationContext context, TypedParam semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.TYPED_PARAM__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.TYPED_PARAM__TYPE));
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.TYPED_PARAM__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.TYPED_PARAM__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypedParamAccess().getTypeDataTypeParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getTypedParamAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns VariableRef
	 *     OrExpression returns VariableRef
	 *     OrExpression.OrExpression_1_0 returns VariableRef
	 *     AndExpression returns VariableRef
	 *     AndExpression.AndExpression_1_0 returns VariableRef
	 *     EqualityExpression returns VariableRef
	 *     EqualityExpression.EqualityExpression_1_0 returns VariableRef
	 *     ComparisonExpression returns VariableRef
	 *     ComparisonExpression.ComparisonExpression_1_0 returns VariableRef
	 *     AdditiveExpression returns VariableRef
	 *     AdditiveExpression.AdditiveExpression_1_0 returns VariableRef
	 *     MultiplicativeExpression returns VariableRef
	 *     MultiplicativeExpression.MultiplicativeExpression_1_0 returns VariableRef
	 *     PrimaryExpression returns VariableRef
	 *     VariableRef returns VariableRef
	 *
	 * Constraint:
	 *     var=ID
	 * </pre>
	 */
	protected void sequence_VariableRef(ISerializationContext context, VariableRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, JarvisProjectPackage.Literals.VARIABLE_REF__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, JarvisProjectPackage.Literals.VARIABLE_REF__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableRefAccess().getVarIDTerminalRuleCall_1_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns While
	 *     While returns While
	 *
	 * Constraint:
	 *     (condition=Expression statements+=Statement+)
	 * </pre>
	 */
	protected void sequence_While(ISerializationContext context, While semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
